/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.anaptecs.jeaf.openapi;

import java.util.Objects;
import java.util.Arrays;
import com.anaptecs.jeaf.openapi.BookingID;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ComplexBookingID
 */


public class ComplexBookingID {
  @JsonProperty("referenceID")
  private String referenceID = null;

  @JsonProperty("internalID")
  private Long internalID = null;

  @JsonProperty("bookingIDs")
  private List<BookingID> bookingIDs = new ArrayList<>();

  @JsonProperty("complexBookingType")
  private String complexBookingType = null;

  public ComplexBookingID referenceID(String referenceID) {
    this.referenceID = referenceID;
    return this;
  }

   /**
   * Get referenceID
   * @return referenceID
  **/
  @Schema(required = true, description = "")
  public String getReferenceID() {
    return referenceID;
  }

  public void setReferenceID(String referenceID) {
    this.referenceID = referenceID;
  }

  public ComplexBookingID internalID(Long internalID) {
    this.internalID = internalID;
    return this;
  }

   /**
   * Get internalID
   * @return internalID
  **/
  @Schema(required = true, description = "")
  public Long getInternalID() {
    return internalID;
  }

  public void setInternalID(Long internalID) {
    this.internalID = internalID;
  }

  public ComplexBookingID bookingIDs(List<BookingID> bookingIDs) {
    this.bookingIDs = bookingIDs;
    return this;
  }

  public ComplexBookingID addBookingIDsItem(BookingID bookingIDsItem) {
    this.bookingIDs.add(bookingIDsItem);
    return this;
  }

   /**
   * Get bookingIDs
   * @return bookingIDs
  **/
  @Schema(required = true, description = "")
  public List<BookingID> getBookingIDs() {
    return bookingIDs;
  }

  public void setBookingIDs(List<BookingID> bookingIDs) {
    this.bookingIDs = bookingIDs;
  }

  public ComplexBookingID complexBookingType(String complexBookingType) {
    this.complexBookingType = complexBookingType;
    return this;
  }

   /**
   * Get complexBookingType
   * @return complexBookingType
  **/
  @Schema(required = true, description = "")
  public String getComplexBookingType() {
    return complexBookingType;
  }

  public void setComplexBookingType(String complexBookingType) {
    this.complexBookingType = complexBookingType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComplexBookingID complexBookingID = (ComplexBookingID) o;
    return Objects.equals(this.referenceID, complexBookingID.referenceID) &&
        Objects.equals(this.internalID, complexBookingID.internalID) &&
        Objects.equals(this.bookingIDs, complexBookingID.bookingIDs) &&
        Objects.equals(this.complexBookingType, complexBookingID.complexBookingType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceID, internalID, bookingIDs, complexBookingType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComplexBookingID {\n");
    
    sb.append("    referenceID: ").append(toIndentedString(referenceID)).append("\n");
    sb.append("    internalID: ").append(toIndentedString(internalID)).append("\n");
    sb.append("    bookingIDs: ").append(toIndentedString(bookingIDs)).append("\n");
    sb.append("    complexBookingType: ").append(toIndentedString(complexBookingType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
