/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.anaptecs.jeaf.openapi;

import java.util.Objects;
import java.util.Arrays;
import com.anaptecs.jeaf.openapi.Message;
import com.anaptecs.jeaf.openapi.MyBusinessObject;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * DoSomethingResponse
 */


public class DoSomethingResponse {
  @JsonProperty("errors")
  private List<Message> errors = null;

  @JsonProperty("warnings")
  private List<Message> warnings = null;

  @JsonProperty("value")
  private MyBusinessObject value = null;

  public DoSomethingResponse errors(List<Message> errors) {
    this.errors = errors;
    return this;
  }

  public DoSomethingResponse addErrorsItem(Message errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @Schema(description = "")
  public List<Message> getErrors() {
    return errors;
  }

  public void setErrors(List<Message> errors) {
    this.errors = errors;
  }

  public DoSomethingResponse warnings(List<Message> warnings) {
    this.warnings = warnings;
    return this;
  }

  public DoSomethingResponse addWarningsItem(Message warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

   /**
   * Get warnings
   * @return warnings
  **/
  @Schema(description = "")
  public List<Message> getWarnings() {
    return warnings;
  }

  public void setWarnings(List<Message> warnings) {
    this.warnings = warnings;
  }

  public DoSomethingResponse value(MyBusinessObject value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(required = true, description = "")
  public MyBusinessObject getValue() {
    return value;
  }

  public void setValue(MyBusinessObject value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoSomethingResponse doSomethingResponse = (DoSomethingResponse) o;
    return Objects.equals(this.errors, doSomethingResponse.errors) &&
        Objects.equals(this.warnings, doSomethingResponse.warnings) &&
        Objects.equals(this.value, doSomethingResponse.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, warnings, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoSomethingResponse {\n");
    
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
