/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.anaptecs.jeaf.openapi;

import java.util.Objects;
import java.util.Arrays;
import com.anaptecs.jeaf.openapi.Message;
import com.anaptecs.jeaf.openapi.TemplateEnumTest;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * MultiTemplateClassImpl
 */


public class MultiTemplateClassImpl {
  @JsonProperty("object")
  private Message object = null;

  @JsonProperty("previousState")
  private TemplateEnumTest previousState = null;

  @JsonProperty("newState")
  private TemplateEnumTest newState = null;

  public MultiTemplateClassImpl object(Message object) {
    this.object = object;
    return this;
  }

   /**
   * Get object
   * @return object
  **/
  @Schema(required = true, description = "")
  public Message getObject() {
    return object;
  }

  public void setObject(Message object) {
    this.object = object;
  }

  public MultiTemplateClassImpl previousState(TemplateEnumTest previousState) {
    this.previousState = previousState;
    return this;
  }

   /**
   * Get previousState
   * @return previousState
  **/
  @Schema(description = "")
  public TemplateEnumTest getPreviousState() {
    return previousState;
  }

  public void setPreviousState(TemplateEnumTest previousState) {
    this.previousState = previousState;
  }

  public MultiTemplateClassImpl newState(TemplateEnumTest newState) {
    this.newState = newState;
    return this;
  }

   /**
   * Get newState
   * @return newState
  **/
  @Schema(required = true, description = "")
  public TemplateEnumTest getNewState() {
    return newState;
  }

  public void setNewState(TemplateEnumTest newState) {
    this.newState = newState;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiTemplateClassImpl multiTemplateClassImpl = (MultiTemplateClassImpl) o;
    return Objects.equals(this.object, multiTemplateClassImpl.object) &&
        Objects.equals(this.previousState, multiTemplateClassImpl.previousState) &&
        Objects.equals(this.newState, multiTemplateClassImpl.newState);
  }

  @Override
  public int hashCode() {
    return Objects.hash(object, previousState, newState);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiTemplateClassImpl {\n");
    
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    previousState: ").append(toIndentedString(previousState)).append("\n");
    sb.append("    newState: ").append(toIndentedString(newState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
