/*
 * Product Services
 * This component represents the OpenAPI interface of the accounting service.<br> <br> Dear Developers, please be aware that multi line comments can also be used. 
 *
 * OpenAPI spec version: 1.28.3-SNAPSHOT
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.anaptecs.jeaf.openapi;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * SoftLinkPartner
 */


public class SoftLinkPartner {
  @JsonProperty("theBackLinkID")
  private String theBackLinkID = null;

  @JsonProperty("childLinkIDs")
  private List<String> childLinkIDs = null;

  @JsonProperty("longLinkIDs")
  private List<Long> longLinkIDs = new ArrayList<>();

  @JsonProperty("derivedSoftLinkID")
  private String derivedSoftLinkID = null;

  @JsonProperty("theDerivedSoftLinkIDs")
  private List<String> theDerivedSoftLinkIDs = null;

  public SoftLinkPartner theBackLinkID(String theBackLinkID) {
    this.theBackLinkID = theBackLinkID;
    return this;
  }

   /**
   * Get theBackLinkID
   * @return theBackLinkID
  **/
  @Schema(description = "")
  public String getTheBackLinkID() {
    return theBackLinkID;
  }

  public void setTheBackLinkID(String theBackLinkID) {
    this.theBackLinkID = theBackLinkID;
  }

  public SoftLinkPartner childLinkIDs(List<String> childLinkIDs) {
    this.childLinkIDs = childLinkIDs;
    return this;
  }

  public SoftLinkPartner addChildLinkIDsItem(String childLinkIDsItem) {
    if (this.childLinkIDs == null) {
      this.childLinkIDs = new ArrayList<>();
    }
    this.childLinkIDs.add(childLinkIDsItem);
    return this;
  }

   /**
   * Get childLinkIDs
   * @return childLinkIDs
  **/
  @Schema(description = "")
  public List<String> getChildLinkIDs() {
    return childLinkIDs;
  }

  public void setChildLinkIDs(List<String> childLinkIDs) {
    this.childLinkIDs = childLinkIDs;
  }

  public SoftLinkPartner longLinkIDs(List<Long> longLinkIDs) {
    this.longLinkIDs = longLinkIDs;
    return this;
  }

  public SoftLinkPartner addLongLinkIDsItem(Long longLinkIDsItem) {
    this.longLinkIDs.add(longLinkIDsItem);
    return this;
  }

   /**
   * Get longLinkIDs
   * @return longLinkIDs
  **/
  @Schema(required = true, description = "")
  public List<Long> getLongLinkIDs() {
    return longLinkIDs;
  }

  public void setLongLinkIDs(List<Long> longLinkIDs) {
    this.longLinkIDs = longLinkIDs;
  }

  public SoftLinkPartner derivedSoftLinkID(String derivedSoftLinkID) {
    this.derivedSoftLinkID = derivedSoftLinkID;
    return this;
  }

   /**
   * Get derivedSoftLinkID
   * @return derivedSoftLinkID
  **/
  @Schema(required = true, description = "")
  public String getDerivedSoftLinkID() {
    return derivedSoftLinkID;
  }

  public void setDerivedSoftLinkID(String derivedSoftLinkID) {
    this.derivedSoftLinkID = derivedSoftLinkID;
  }

  public SoftLinkPartner theDerivedSoftLinkIDs(List<String> theDerivedSoftLinkIDs) {
    this.theDerivedSoftLinkIDs = theDerivedSoftLinkIDs;
    return this;
  }

  public SoftLinkPartner addTheDerivedSoftLinkIDsItem(String theDerivedSoftLinkIDsItem) {
    if (this.theDerivedSoftLinkIDs == null) {
      this.theDerivedSoftLinkIDs = new ArrayList<>();
    }
    this.theDerivedSoftLinkIDs.add(theDerivedSoftLinkIDsItem);
    return this;
  }

   /**
   * Get theDerivedSoftLinkIDs
   * @return theDerivedSoftLinkIDs
  **/
  @Schema(description = "")
  public List<String> getTheDerivedSoftLinkIDs() {
    return theDerivedSoftLinkIDs;
  }

  public void setTheDerivedSoftLinkIDs(List<String> theDerivedSoftLinkIDs) {
    this.theDerivedSoftLinkIDs = theDerivedSoftLinkIDs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SoftLinkPartner softLinkPartner = (SoftLinkPartner) o;
    return Objects.equals(this.theBackLinkID, softLinkPartner.theBackLinkID) &&
        Objects.equals(this.childLinkIDs, softLinkPartner.childLinkIDs) &&
        Objects.equals(this.longLinkIDs, softLinkPartner.longLinkIDs) &&
        Objects.equals(this.derivedSoftLinkID, softLinkPartner.derivedSoftLinkID) &&
        Objects.equals(this.theDerivedSoftLinkIDs, softLinkPartner.theDerivedSoftLinkIDs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(theBackLinkID, childLinkIDs, longLinkIDs, derivedSoftLinkID, theDerivedSoftLinkIDs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SoftLinkPartner {\n");
    
    sb.append("    theBackLinkID: ").append(toIndentedString(theBackLinkID)).append("\n");
    sb.append("    childLinkIDs: ").append(toIndentedString(childLinkIDs)).append("\n");
    sb.append("    longLinkIDs: ").append(toIndentedString(longLinkIDs)).append("\n");
    sb.append("    derivedSoftLinkID: ").append(toIndentedString(derivedSoftLinkID)).append("\n");
    sb.append("    theDerivedSoftLinkIDs: ").append(toIndentedString(theDerivedSoftLinkIDs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
