/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.anaptecs.jeaf.openapi;

import java.util.Objects;
import java.util.Arrays;
import com.anaptecs.jeaf.openapi.Product;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Sortiment
 */


public class Sortiment {
  @JsonProperty("products")
  private List<Product> products = null;

  @JsonProperty("value")
  private Integer value = 4711;

  @JsonProperty("inlineSortimentType")
  private String inlineSortimentType = null;

  public Sortiment products(List<Product> products) {
    this.products = products;
    return this;
  }

  public Sortiment addProductsItem(Product productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * Get products
   * @return products
  **/
  @Schema(description = "")
  public List<Product> getProducts() {
    return products;
  }

  public void setProducts(List<Product> products) {
    this.products = products;
  }

  public Sortiment value(Integer value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(required = true, description = "")
  public Integer getValue() {
    return value;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Sortiment inlineSortimentType(String inlineSortimentType) {
    this.inlineSortimentType = inlineSortimentType;
    return this;
  }

   /**
   * Get inlineSortimentType
   * @return inlineSortimentType
  **/
  @Schema(description = "")
  public String getInlineSortimentType() {
    return inlineSortimentType;
  }

  public void setInlineSortimentType(String inlineSortimentType) {
    this.inlineSortimentType = inlineSortimentType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sortiment sortiment = (Sortiment) o;
    return Objects.equals(this.products, sortiment.products) &&
        Objects.equals(this.value, sortiment.value) &&
        Objects.equals(this.inlineSortimentType, sortiment.inlineSortimentType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(products, value, inlineSortimentType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sortiment {\n");
    
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    inlineSortimentType: ").append(toIndentedString(inlineSortimentType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
