/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.anaptecs.jeaf.openapi;

import java.util.Objects;
import java.util.Arrays;
import com.anaptecs.jeaf.openapi.LinkObject;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeId;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Stop
 */

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "objectType", visible = true )
@JsonSubTypes({
  @JsonSubTypes.Type(value = UICStop.class, name = "UICStop"),
  @JsonSubTypes.Type(value = POI.class, name = "POI"),
})

public class Stop {
  @JsonTypeId
  private String objectType = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("_links")
  private List<LinkObject> _links = null;

  @JsonProperty("index")
  private Integer index = null;

  @JsonProperty("theSoftLinkID")
  private String theSoftLinkID = null;

  public Stop objectType(String objectType) {
    this.objectType = objectType;
    return this;
  }

   /**
   * Attribute is used as discriminator for inheritance between data types.
   * @return objectType
  **/
  @Schema(required = true, description = "Attribute is used as discriminator for inheritance between data types.")
  public String getObjectType() {
    return objectType;
  }

  public void setObjectType(String objectType) {
    this.objectType = objectType;
  }

  public Stop name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Stop _links(List<LinkObject> _links) {
    this._links = _links;
    return this;
  }

  public Stop addLinksItem(LinkObject _linksItem) {
    if (this._links == null) {
      this._links = new ArrayList<>();
    }
    this._links.add(_linksItem);
    return this;
  }

   /**
   *  Java Property Name: &#x27;links&#x27;  
   * @return _links
  **/
  @Schema(description = " Java Property Name: 'links'  ")
  public List<LinkObject> getLinks() {
    return _links;
  }

  public void setLinks(List<LinkObject> _links) {
    this._links = _links;
  }

  public Stop index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Get index
   * minimum: 0
   * maximum: 32
   * @return index
  **/
  @Schema(required = true, description = "")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public Stop theSoftLinkID(String theSoftLinkID) {
    this.theSoftLinkID = theSoftLinkID;
    return this;
  }

   /**
   * Get theSoftLinkID
   * @return theSoftLinkID
  **/
  @Schema(required = true, description = "")
  public String getTheSoftLinkID() {
    return theSoftLinkID;
  }

  public void setTheSoftLinkID(String theSoftLinkID) {
    this.theSoftLinkID = theSoftLinkID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Stop stop = (Stop) o;
    return Objects.equals(this.objectType, stop.objectType) &&
        Objects.equals(this.name, stop.name) &&
        Objects.equals(this._links, stop._links) &&
        Objects.equals(this.index, stop.index) &&
        Objects.equals(this.theSoftLinkID, stop.theSoftLinkID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectType, name, _links, index, theSoftLinkID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Stop {\n");
    
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    theSoftLinkID: ").append(toIndentedString(theSoftLinkID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
