/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.anaptecs.jeaf.openapi;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Enumeration represents time units.       NOVA 14 Mapping * nova-base.xsd.ZeitEinheit Alternate Name: Zeiteinheit Valid Values: - MINUTE: Literal represents time unit \&quot;minutes\&quot;. - HOUR - DAY - WEEK: Literal represents time unit \&quot;weeks\&quot;.     This is the comments second line ;-) - MONTH - YEAR 
 */
public enum TimeUnit {
  MINUTE("MINUTE"),
  HOUR("HOUR"),
  DAY("DAY"),
  WEEK("WEEK"),
  MONTH("MONTH"),
  YEAR("YEAR");

  private String value;

  TimeUnit(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TimeUnit fromValue(String input) {
    for (TimeUnit b : TimeUnit.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
