/*
 * anaptecs GmbH, Ricarda-Huch-Str. 71, 72760 Reutlingen, Germany
 * 
 * Copyright 2004 - 2019. All rights reserved.
 */
package com.anaptecs.jeaf.junit.impl.persistence;

import java.util.Set;

import com.anaptecs.jeaf.core.api.Component;
import com.anaptecs.jeaf.core.api.ServiceObjectID;
import com.anaptecs.jeaf.core.spi.CheckLevel;
import com.anaptecs.jeaf.core.spi.CheckResult;
import com.anaptecs.jeaf.junit.core.ClassA;

/**
 * Implementation of BusinessObjectTestService.
 */
final class BusinessObjectTestServiceImpl extends BusinessObjectTestServiceImplBase {
  /**
   * Initialize object.
   */
  BusinessObjectTestServiceImpl( Component pComponent ) {
    super(pComponent);
  }

  /**
   * Method checks the current state of the service. Therefore JEAF defines three different check levels: internal
   * Checks, infrastructure checks and external checks. For further details about the check levels {@see CheckLevel}.
   * 
   * 
   * @param pLevel Check level on which the check should be performed. The parameter is never null.
   * @return {@link CheckResult} Object describing the result of the check. The method may return null. This means that
   * the service does not implement any checks. In order to use as less memory as possible the method should use the
   * constant CheckResult.CHECK_OK if no errors or warnings occurred during the check.
   * 
   * @see CheckResult#CHECK_OK
   */
  public CheckResult check( CheckLevel pLevel ) {
    // TODO Implement checks for this service
    return null;
  }

  /**
  * 
  */
  @Override
  public void testAttributeAccess( ) {
  }

  /**
  * 
  */
  @Override
  public void testBusinessMethods( ) {
  }

  /**
   * Method tests the business objects that are generated by the JEAF Generator. This test cases cares about
   * many-to-many associations between service objects.
   * 
   * 
   */
  @Override
  public void testBusinessObjectsWithManyToManyAssociations( ) {
  }

  /**
   * Method tests the business objects that are generated by the JEAF Generator. This test cases cares about one-to-many
   * associations between service objects.
   * 
   * 
   */
  @Override
  public void testServiceObjectsWithOneToManyAssociations( ) {
  }

  /**
   * Method tests the business objects that are generated by the JEAF Generator. This test cases cares about one-to-one
   * associations between service objects.
   * 
   * 
   */
  @Override
  public void testServiceObjectsWithOneToOneAssociations( ) {
  }

  /**
  * 
  */
  @Override
  public void testCreateSimpleBusinessObject( ) {
  }

  /**
  * 
  */
  @Override
  public void testBusinessObjectsWithInheritance( ) {
  }

  /**
  * 
  */
  @Override
  public void testMToNReleation( ) {
  }

  /**
   * Method updates the business object with the passed id.
   * 
   * 
   * @param pServiceObjectID
   * @return {@link Integer}
   */
  @Override
  public Integer updateBusinessObject( ServiceObjectID pServiceObjectID ) {
    // TODO Implement method and return real result
    return null;
  }

  /**
   * 
   * @return {@link ServiceObjectID}
   */
  @Override
  public ServiceObjectID createBusinessObject( ) {
    // TODO Implement method and return real result
    return null;
  }

  /**
   * 
   * @param pServiceObjectID
   */
  @Override
  public void deleteBusinessObject( ServiceObjectID pServiceObjectID ) {
  }

  /**
  * 
  */
  @Override
  public void testQueryWithJPAQL( ) {
  }

  /**
  * 
  */
  @Override
  public void testAOneToBOne( ) {
  }

  /**
  * 
  */
  @Override
  public void testBOneToAOne( ) {
  }

  /**
  * 
  */
  @Override
  public void createXOne( ) {
  }

  /**
   * 
   * @return {@link ServiceObjectID}
   */
  @Override
  public ServiceObjectID createABCObjects( ) {
    // TODO Implement method and return real result
    return null;
  }

  /**
  * 
  */
  @Override
  public void testNativeQuery( ) {
  }

  /**
   * 
   * @param pBOneID
   * @return {@link ServiceObjectID}
   */
  @Override
  public Set<ServiceObjectID> getCManys( ServiceObjectID pBOneID ) {
    // TODO Implement method and return real result
    return null;
  }

  /**
   * 
   * @param pBOneID
   * @return {@link ServiceObjectID}
   */
  @Override
  public ServiceObjectID addCMany( ServiceObjectID pBOneID ) {
    // TODO Implement method and return real result
    return null;
  }

  /**
   * 
   * @param pBOneID
   */
  @Override
  public void clearCMany( ServiceObjectID pBOneID ) {
  }

  /**
   * 
   * @param pBOneID
   * @param pCManyID
   */
  @Override
  public void removeCMany( ServiceObjectID pBOneID, ServiceObjectID pCManyID ) {
  }

  /**
  * 
  */
  @Override
  public void testDynamicPropertyAccess( ) {
  }

  /**
  * 
  */
  @Override
  public void testCreateBusinessObjectsWithUserTypeMapping( ) {
  }

  /**
  * 
  */
  @Override
  public void testReadBusinessObjectsWithUserTypeMapping( ) {
  }

  /**
   * 
   * @param pClassA
   * @return {@link ClassA}
   */
  @Override
  public ClassA createClassA( ClassA pClassA ) {
    // TODO Implement method and return real result
    return null;
  }

  /**
   * 
   * @param pClassA
   */
  @Override
  public void updateClassA( ClassA pClassA ) {
  }

  /**
   * 
   * @param pServiceObjectID
   * @return {@link ClassA}
   */
  @Override
  public ClassA getClassA( ServiceObjectID pServiceObjectID ) {
    // TODO Implement method and return real result
    return null;
  }

  /**
  * 
  */
  @Override
  public void testInitialObjectCache( ) {
  }

  /**
  * 
  */
  @Override
  public void testObjectCacheReloading( ) {
  }

  /**
  * 
  */
  @Override
  public void testJDBCWorker( ) {
  }

  /**
   * 
   * @param pFail
   */
  @Override
  public void testTransactionListener( boolean pFail ) {
  }

  /**
  * 
  */
  @Override
  public void testFlush( ) {
  }
}
