/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import openapitools.model.DoSomethingResponse;
import openapitools.model.MultiTemplateClassImpl;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * AndOneMorePOJO
 */
@JsonPropertyOrder({
  AndOneMorePOJO.JSON_PROPERTY_GENERIC_PROPERTY,
  AndOneMorePOJO.JSON_PROPERTY_GENERIC_RESPONSES,
  AndOneMorePOJO.JSON_PROPERTY_MULTI_TEMPLATE_CLASS_IMPL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class AndOneMorePOJO {
  public static final String JSON_PROPERTY_GENERIC_PROPERTY = "genericProperty";
  @javax.annotation.Nonnull
  private DoSomethingResponse genericProperty;

  public static final String JSON_PROPERTY_GENERIC_RESPONSES = "genericResponses";
  @javax.annotation.Nullable
  private List<DoSomethingResponse> genericResponses = new ArrayList<>();

  public static final String JSON_PROPERTY_MULTI_TEMPLATE_CLASS_IMPL = "multiTemplateClassImpl";
  @javax.annotation.Nonnull
  private MultiTemplateClassImpl multiTemplateClassImpl;

  public AndOneMorePOJO() { 
  }

  public AndOneMorePOJO genericProperty(@javax.annotation.Nonnull DoSomethingResponse genericProperty) {
    this.genericProperty = genericProperty;
    return this;
  }

  /**
   * Get genericProperty
   * @return genericProperty
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GENERIC_PROPERTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public DoSomethingResponse getGenericProperty() {
    return genericProperty;
  }


  @JsonProperty(JSON_PROPERTY_GENERIC_PROPERTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGenericProperty(@javax.annotation.Nonnull DoSomethingResponse genericProperty) {
    this.genericProperty = genericProperty;
  }


  public AndOneMorePOJO genericResponses(@javax.annotation.Nullable List<DoSomethingResponse> genericResponses) {
    this.genericResponses = genericResponses;
    return this;
  }

  public AndOneMorePOJO addGenericResponsesItem(DoSomethingResponse genericResponsesItem) {
    if (this.genericResponses == null) {
      this.genericResponses = new ArrayList<>();
    }
    this.genericResponses.add(genericResponsesItem);
    return this;
  }

  /**
   * Get genericResponses
   * @return genericResponses
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GENERIC_RESPONSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoSomethingResponse> getGenericResponses() {
    return genericResponses;
  }


  @JsonProperty(JSON_PROPERTY_GENERIC_RESPONSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGenericResponses(@javax.annotation.Nullable List<DoSomethingResponse> genericResponses) {
    this.genericResponses = genericResponses;
  }


  public AndOneMorePOJO multiTemplateClassImpl(@javax.annotation.Nonnull MultiTemplateClassImpl multiTemplateClassImpl) {
    this.multiTemplateClassImpl = multiTemplateClassImpl;
    return this;
  }

  /**
   * Get multiTemplateClassImpl
   * @return multiTemplateClassImpl
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MULTI_TEMPLATE_CLASS_IMPL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MultiTemplateClassImpl getMultiTemplateClassImpl() {
    return multiTemplateClassImpl;
  }


  @JsonProperty(JSON_PROPERTY_MULTI_TEMPLATE_CLASS_IMPL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMultiTemplateClassImpl(@javax.annotation.Nonnull MultiTemplateClassImpl multiTemplateClassImpl) {
    this.multiTemplateClassImpl = multiTemplateClassImpl;
  }


  /**
   * Return true if this AndOneMorePOJO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AndOneMorePOJO andOneMorePOJO = (AndOneMorePOJO) o;
    return Objects.equals(this.genericProperty, andOneMorePOJO.genericProperty) &&
        Objects.equals(this.genericResponses, andOneMorePOJO.genericResponses) &&
        Objects.equals(this.multiTemplateClassImpl, andOneMorePOJO.multiTemplateClassImpl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(genericProperty, genericResponses, multiTemplateClassImpl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AndOneMorePOJO {\n");
    sb.append("    genericProperty: ").append(toIndentedString(genericProperty)).append("\n");
    sb.append("    genericResponses: ").append(toIndentedString(genericResponses)).append("\n");
    sb.append("    multiTemplateClassImpl: ").append(toIndentedString(multiTemplateClassImpl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

