/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * Booking
 */
@JsonPropertyOrder({
  Booking.JSON_PROPERTY_BOOKING_I_D
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class Booking {
  public static final String JSON_PROPERTY_BOOKING_I_D = "bookingID";
  @javax.annotation.Nonnull
  private String bookingID;

  public Booking() { 
  }

  public Booking bookingID(@javax.annotation.Nonnull String bookingID) {
    this.bookingID = bookingID;
    return this;
  }

  /**
   * ID of the booking 
   * @return bookingID
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BOOKING_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBookingID() {
    return bookingID;
  }


  @JsonProperty(value = JSON_PROPERTY_BOOKING_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBookingID(@javax.annotation.Nonnull String bookingID) {
    this.bookingID = bookingID;
  }


  /**
   * Return true if this Booking object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Booking booking = (Booking) o;
    return Objects.equals(this.bookingID, booking.bookingID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bookingID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Booking {\n");
    sb.append("    bookingID: ").append(toIndentedString(bookingID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

