/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets BooleanLiteralsEnum
 */
public enum BooleanLiteralsEnum {
  
  YES("YES"),
  
  ON("ON"),
  
  OFF("off"),
  
  Y("y"),
  
  N("n"),
  
  YEAH("YEAH"),
  
  NO("NO"),
  
  TRUE("True"),
  
  FALSE("FaLsE");

  private String value;

  BooleanLiteralsEnum(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static BooleanLiteralsEnum fromValue(String value) {
    for (BooleanLiteralsEnum b : BooleanLiteralsEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

