/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * BusinessParent
 */
@JsonPropertyOrder({
  BusinessParent.JSON_PROPERTY_OBJECT_TYPE,
  BusinessParent.JSON_PROPERTY_PARENT_ATTRIBUTE,
  BusinessParent.JSON_PROPERTY_TECH_ATTRIBUTE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
@JsonIgnoreProperties(
  value = "objectType", // ignore manually set objectType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the objectType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "objectType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = BusinessChild.class, name = "BusinessChild"),
})

public class BusinessParent {
  public static final String JSON_PROPERTY_OBJECT_TYPE = "objectType";
  @javax.annotation.Nonnull
  private String objectType;

  public static final String JSON_PROPERTY_PARENT_ATTRIBUTE = "parentAttribute";
  @javax.annotation.Nonnull
  private Long parentAttribute;

  public static final String JSON_PROPERTY_TECH_ATTRIBUTE = "techAttribute";
  @javax.annotation.Nonnull
  private String techAttribute;

  public BusinessParent() { 
  }

  public BusinessParent objectType(@javax.annotation.Nonnull String objectType) {
    this.objectType = objectType;
    return this;
  }

  /**
   * Attribute is used as discriminator for inheritance between data types.
   * @return objectType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getObjectType() {
    return objectType;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObjectType(@javax.annotation.Nonnull String objectType) {
    this.objectType = objectType;
  }


  public BusinessParent parentAttribute(@javax.annotation.Nonnull Long parentAttribute) {
    this.parentAttribute = parentAttribute;
    return this;
  }

  /**
   * Get parentAttribute
   * @return parentAttribute
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARENT_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getParentAttribute() {
    return parentAttribute;
  }


  @JsonProperty(JSON_PROPERTY_PARENT_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParentAttribute(@javax.annotation.Nonnull Long parentAttribute) {
    this.parentAttribute = parentAttribute;
  }


  public BusinessParent techAttribute(@javax.annotation.Nonnull String techAttribute) {
    this.techAttribute = techAttribute;
    return this;
  }

  /**
   * Get techAttribute
   * @return techAttribute
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TECH_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTechAttribute() {
    return techAttribute;
  }


  @JsonProperty(JSON_PROPERTY_TECH_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTechAttribute(@javax.annotation.Nonnull String techAttribute) {
    this.techAttribute = techAttribute;
  }


  /**
   * Return true if this BusinessParent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessParent businessParent = (BusinessParent) o;
    return Objects.equals(this.objectType, businessParent.objectType) &&
        Objects.equals(this.parentAttribute, businessParent.parentAttribute) &&
        Objects.equals(this.techAttribute, businessParent.techAttribute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectType, parentAttribute, techAttribute);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessParent {\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    parentAttribute: ").append(toIndentedString(parentAttribute)).append("\n");
    sb.append("    techAttribute: ").append(toIndentedString(techAttribute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  static {
    // Initialize and register the discriminator mappings.
    Map<String, Class<?>> mappings = new HashMap<>();
    mappings.put("BusinessChild", BusinessChild.class);
    mappings.put("BusinessParent", BusinessParent.class);
    JSON.registerDiscriminator(BusinessParent.class, "objectType", mappings);
  }
}

