/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * Campaign
 */
@JsonPropertyOrder({
  Campaign.JSON_PROPERTY_THE_LINK,
  Campaign.JSON_PROPERTY_MORE_LINKS,
  Campaign.JSON_PROPERTY_DISCOUNT_OFFERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class Campaign {
  public static final String JSON_PROPERTY_THE_LINK = "theLink";
  private JsonNullable<Long> theLink = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_MORE_LINKS = "moreLinks";
  private List<Long> moreLinks = new ArrayList<>();

  public static final String JSON_PROPERTY_DISCOUNT_OFFERS = "discountOffers";
  private JsonNullable<List<String>> discountOffers = JsonNullable.<List<String>>undefined();

  public Campaign() { 
  }

  public Campaign theLink(Long theLink) {
    this.theLink = JsonNullable.<Long>of(theLink);
    return this;
  }

   /**
   * Get theLink
   * @return theLink
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nullable
  @JsonIgnore

  public Long getTheLink() {
        return theLink.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_THE_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getTheLink_JsonNullable() {
    return theLink;
  }
  
  @JsonProperty(JSON_PROPERTY_THE_LINK)
  public void setTheLink_JsonNullable(JsonNullable<Long> theLink) {
    this.theLink = theLink;
  }

  public void setTheLink(Long theLink) {
    this.theLink = JsonNullable.<Long>of(theLink);
  }


  public Campaign moreLinks(List<Long> moreLinks) {
    this.moreLinks = moreLinks;
    return this;
  }

  public Campaign addMoreLinksItem(Long moreLinksItem) {
    if (this.moreLinks == null) {
      this.moreLinks = new ArrayList<>();
    }
    this.moreLinks.add(moreLinksItem);
    return this;
  }

   /**
   *  Deprecated: No good any more (since: 1.2, removed with: 3.0) 
   * @return moreLinks
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MORE_LINKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Long> getMoreLinks() {
    return moreLinks;
  }


  @JsonProperty(JSON_PROPERTY_MORE_LINKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMoreLinks(List<Long> moreLinks) {
    this.moreLinks = moreLinks;
  }


  public Campaign discountOffers(List<String> discountOffers) {
    this.discountOffers = JsonNullable.<List<String>>of(discountOffers);
    return this;
  }

  public Campaign addDiscountOffersItem(String discountOffersItem) {
    if (this.discountOffers == null || !this.discountOffers.isPresent()) {
      this.discountOffers = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.discountOffers.get().add(discountOffersItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

   /**
   * Get discountOffers
   * @return discountOffers
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nullable
  @JsonIgnore

  public List<String> getDiscountOffers() {
        return discountOffers.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DISCOUNT_OFFERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getDiscountOffers_JsonNullable() {
    return discountOffers;
  }
  
  @JsonProperty(JSON_PROPERTY_DISCOUNT_OFFERS)
  public void setDiscountOffers_JsonNullable(JsonNullable<List<String>> discountOffers) {
    this.discountOffers = discountOffers;
  }

  public void setDiscountOffers(List<String> discountOffers) {
    this.discountOffers = JsonNullable.<List<String>>of(discountOffers);
  }


  /**
   * Return true if this Campaign object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Campaign campaign = (Campaign) o;
    return equalsNullable(this.theLink, campaign.theLink) &&
        Objects.equals(this.moreLinks, campaign.moreLinks) &&
        equalsNullable(this.discountOffers, campaign.discountOffers);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(theLink), moreLinks, hashCodeNullable(discountOffers));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Campaign {\n");
    sb.append("    theLink: ").append(toIndentedString(theLink)).append("\n");
    sb.append("    moreLinks: ").append(toIndentedString(moreLinks)).append("\n");
    sb.append("    discountOffers: ").append(toIndentedString(discountOffers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

