/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * Campaign
 */
@JsonPropertyOrder({
  Campaign.JSON_PROPERTY_THE_LINK,
  Campaign.JSON_PROPERTY_MORE_LINKS,
  Campaign.JSON_PROPERTY_DISCOUNT_OFFERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Campaign {
  public static final String JSON_PROPERTY_THE_LINK = "theLink";
  private Long theLink;

  public static final String JSON_PROPERTY_MORE_LINKS = "moreLinks";
  private List<Long> moreLinks = new ArrayList<>();

  public static final String JSON_PROPERTY_DISCOUNT_OFFERS = "discountOffers";
  private List<String> discountOffers = null;

  public Campaign() { 
  }

  public Campaign theLink(Long theLink) {
    this.theLink = theLink;
    return this;
  }

   /**
   * Get theLink
   * @return theLink
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_THE_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTheLink() {
    return theLink;
  }


  @JsonProperty(JSON_PROPERTY_THE_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTheLink(Long theLink) {
    this.theLink = theLink;
  }


  public Campaign moreLinks(List<Long> moreLinks) {
    this.moreLinks = moreLinks;
    return this;
  }

  public Campaign addMoreLinksItem(Long moreLinksItem) {
    this.moreLinks.add(moreLinksItem);
    return this;
  }

   /**
   *  Deprecated: No good any more(since: 1.2, removed with: 3.0) 
   * @return moreLinks
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = " Deprecated: No good any more(since: 1.2, removed with: 3.0) ")
  @JsonProperty(JSON_PROPERTY_MORE_LINKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Long> getMoreLinks() {
    return moreLinks;
  }


  @JsonProperty(JSON_PROPERTY_MORE_LINKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMoreLinks(List<Long> moreLinks) {
    this.moreLinks = moreLinks;
  }


  public Campaign discountOffers(List<String> discountOffers) {
    this.discountOffers = discountOffers;
    return this;
  }

  public Campaign addDiscountOffersItem(String discountOffersItem) {
    if (this.discountOffers == null) {
      this.discountOffers = new ArrayList<>();
    }
    this.discountOffers.add(discountOffersItem);
    return this;
  }

   /**
   * Get discountOffers
   * @return discountOffers
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISCOUNT_OFFERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getDiscountOffers() {
    return discountOffers;
  }


  @JsonProperty(JSON_PROPERTY_DISCOUNT_OFFERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscountOffers(List<String> discountOffers) {
    this.discountOffers = discountOffers;
  }


  /**
   * Return true if this Campaign object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Campaign campaign = (Campaign) o;
    return Objects.equals(this.theLink, campaign.theLink) &&
        Objects.equals(this.moreLinks, campaign.moreLinks) &&
        Objects.equals(this.discountOffers, campaign.discountOffers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(theLink, moreLinks, discountOffers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Campaign {\n");
    sb.append("    theLink: ").append(toIndentedString(theLink)).append("\n");
    sb.append("    moreLinks: ").append(toIndentedString(moreLinks)).append("\n");
    sb.append("    discountOffers: ").append(toIndentedString(discountOffers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

