/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 *  &lt;br&gt; Alternate Name: Kanal &lt;br&gt; Valid Values: - COUNTER: counter     &lt;br&gt;     Alternate Name: BEDIENT - CALL_CENTER - MOBILE - TVM - WEB:      &lt;br&gt;     Breaking Change with 1.47.11: Added new literal - @Deprecated LEGACY_POS:      &lt;br&gt;     Deprecated: I&#39;m &#x60;DEPRECATED&#x60;. (since: , removed with: ) 
 */
public enum ChannelType {
  
  COUNTER("COUNTER"),
  
  CALL_CENTER("CALL_CENTER"),
  
  MOBILE("MOBILE"),
  
  TVM("TVM"),
  
  WEB("WEB"),
  
  LEGACY_POS("LEGACY_POS");

  private String value;

  ChannelType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ChannelType fromValue(String value) {
    for (ChannelType b : ChannelType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

