/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import openapitools.model.ChannelType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * Channel
 */
@JsonPropertyOrder({
  Channel.JSON_PROPERTY_CHANNEL_TYPE,
  Channel.JSON_PROPERTY_CHANNEL_CODE,
  Channel.JSON_PROPERTY_CODE,
  Channel.JSON_PROPERTY_SELF_SERVICE_CHANNEL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Channel {
  public static final String JSON_PROPERTY_CHANNEL_TYPE = "channelType";
  @javax.annotation.Nonnull
  private ChannelType channelType = ChannelType.MOBILE;

  public static final String JSON_PROPERTY_CHANNEL_CODE = "channelCode";
  @javax.annotation.Nonnull
  private String channelCode = "WEBSHOP";

  public static final String JSON_PROPERTY_CODE = "code";
  @javax.annotation.Nonnull
  private Integer code;

  public static final String JSON_PROPERTY_SELF_SERVICE_CHANNEL = "selfServiceChannel";
  @javax.annotation.Nonnull
  private Boolean selfServiceChannel = true;

  public Channel() { 
  }

  public Channel channelType(@javax.annotation.Nonnull ChannelType channelType) {
    this.channelType = channelType;
    return this;
  }

  /**
   * Get channelType
   * @return channelType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHANNEL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChannelType getChannelType() {
    return channelType;
  }


  @JsonProperty(JSON_PROPERTY_CHANNEL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChannelType(@javax.annotation.Nonnull ChannelType channelType) {
    this.channelType = channelType;
  }


  public Channel channelCode(@javax.annotation.Nonnull String channelCode) {
    this.channelCode = channelCode;
    return this;
  }

  /**
   * The business code of the channel 
   * @return channelCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHANNEL_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getChannelCode() {
    return channelCode;
  }


  @JsonProperty(JSON_PROPERTY_CHANNEL_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChannelCode(@javax.annotation.Nonnull String channelCode) {
    this.channelCode = channelCode;
  }


  public Channel code(@javax.annotation.Nonnull Integer code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(@javax.annotation.Nonnull Integer code) {
    this.code = code;
  }


  public Channel selfServiceChannel(@javax.annotation.Nonnull Boolean selfServiceChannel) {
    this.selfServiceChannel = selfServiceChannel;
    return this;
  }

  /**
   * Get selfServiceChannel
   * @return selfServiceChannel
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SELF_SERVICE_CHANNEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getSelfServiceChannel() {
    return selfServiceChannel;
  }


  @JsonProperty(JSON_PROPERTY_SELF_SERVICE_CHANNEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSelfServiceChannel(@javax.annotation.Nonnull Boolean selfServiceChannel) {
    this.selfServiceChannel = selfServiceChannel;
  }


  /**
   * Return true if this Channel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Channel channel = (Channel) o;
    return Objects.equals(this.channelType, channel.channelType) &&
        Objects.equals(this.channelCode, channel.channelCode) &&
        Objects.equals(this.code, channel.code) &&
        Objects.equals(this.selfServiceChannel, channel.selfServiceChannel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelType, channelCode, code, selfServiceChannel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Channel {\n");
    sb.append("    channelType: ").append(toIndentedString(channelType)).append("\n");
    sb.append("    channelCode: ").append(toIndentedString(channelCode)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    selfServiceChannel: ").append(toIndentedString(selfServiceChannel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

