/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * ChildAAAllOf
 */
@JsonPropertyOrder({
  ChildAAAllOf.JSON_PROPERTY_CHILD_A_A_ATTRIBUTE,
  ChildAAAllOf.JSON_PROPERTY_SIZED_ARRAY,
  ChildAAAllOf.JSON_PROPERTY_REQUIRED_ARRAY,
  ChildAAAllOf.JSON_PROPERTY_BIG_INTEGER_CODE,
  ChildAAAllOf.JSON_PROPERTY_INTEGER_CODE,
  ChildAAAllOf.JSON_PROPERTY_CODES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ChildAAAllOf {
  public static final String JSON_PROPERTY_CHILD_A_A_ATTRIBUTE = "childAAAttribute";
  private Integer childAAAttribute;

  public static final String JSON_PROPERTY_SIZED_ARRAY = "sizedArray";
  private JsonNullable<List<Integer>> sizedArray = JsonNullable.<List<Integer>>undefined();

  public static final String JSON_PROPERTY_REQUIRED_ARRAY = "requiredArray";
  private List<String> requiredArray = new ArrayList<>();

  public static final String JSON_PROPERTY_BIG_INTEGER_CODE = "bigIntegerCode";
  private Long bigIntegerCode;

  public static final String JSON_PROPERTY_INTEGER_CODE = "integerCode";
  private Integer integerCode;

  public static final String JSON_PROPERTY_CODES = "codes";
  private JsonNullable<List<Integer>> codes = JsonNullable.<List<Integer>>undefined();

  public ChildAAAllOf() { 
  }

  public ChildAAAllOf childAAAttribute(Integer childAAAttribute) {
    this.childAAAttribute = childAAAttribute;
    return this;
  }

   /**
   * Multi line docs 
   * @return childAAAttribute
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Multi line docs ")
  @JsonProperty(JSON_PROPERTY_CHILD_A_A_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getChildAAAttribute() {
    return childAAAttribute;
  }


  @JsonProperty(JSON_PROPERTY_CHILD_A_A_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChildAAAttribute(Integer childAAAttribute) {
    this.childAAAttribute = childAAAttribute;
  }


  public ChildAAAllOf sizedArray(List<Integer> sizedArray) {
    this.sizedArray = JsonNullable.<List<Integer>>of(sizedArray);
    return this;
  }

  public ChildAAAllOf addSizedArrayItem(Integer sizedArrayItem) {
    if (this.sizedArray == null || !this.sizedArray.isPresent()) {
      this.sizedArray = JsonNullable.<List<Integer>>of(new ArrayList<>());
    }
    try {
      this.sizedArray.get().add(sizedArrayItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

   /**
   * Get sizedArray
   * @return sizedArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public List<Integer> getSizedArray() {
        return sizedArray.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SIZED_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Integer>> getSizedArray_JsonNullable() {
    return sizedArray;
  }
  
  @JsonProperty(JSON_PROPERTY_SIZED_ARRAY)
  public void setSizedArray_JsonNullable(JsonNullable<List<Integer>> sizedArray) {
    this.sizedArray = sizedArray;
  }

  public void setSizedArray(List<Integer> sizedArray) {
    this.sizedArray = JsonNullable.<List<Integer>>of(sizedArray);
  }


  public ChildAAAllOf requiredArray(List<String> requiredArray) {
    this.requiredArray = requiredArray;
    return this;
  }

  public ChildAAAllOf addRequiredArrayItem(String requiredArrayItem) {
    this.requiredArray.add(requiredArrayItem);
    return this;
  }

   /**
   * Get requiredArray
   * @return requiredArray
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_REQUIRED_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getRequiredArray() {
    return requiredArray;
  }


  @JsonProperty(JSON_PROPERTY_REQUIRED_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequiredArray(List<String> requiredArray) {
    this.requiredArray = requiredArray;
  }


  public ChildAAAllOf bigIntegerCode(Long bigIntegerCode) {
    this.bigIntegerCode = bigIntegerCode;
    return this;
  }

   /**
   * Get bigIntegerCode
   * maximum: 4711
   * @return bigIntegerCode
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BIG_INTEGER_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getBigIntegerCode() {
    return bigIntegerCode;
  }


  @JsonProperty(JSON_PROPERTY_BIG_INTEGER_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBigIntegerCode(Long bigIntegerCode) {
    this.bigIntegerCode = bigIntegerCode;
  }


  public ChildAAAllOf integerCode(Integer integerCode) {
    this.integerCode = integerCode;
    return this;
  }

   /**
   * Get integerCode
   * @return integerCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INTEGER_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIntegerCode() {
    return integerCode;
  }


  @JsonProperty(JSON_PROPERTY_INTEGER_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntegerCode(Integer integerCode) {
    this.integerCode = integerCode;
  }


  public ChildAAAllOf codes(List<Integer> codes) {
    this.codes = JsonNullable.<List<Integer>>of(codes);
    return this;
  }

  public ChildAAAllOf addCodesItem(Integer codesItem) {
    if (this.codes == null || !this.codes.isPresent()) {
      this.codes = JsonNullable.<List<Integer>>of(new ArrayList<>());
    }
    try {
      this.codes.get().add(codesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

   /**
   * Get codes
   * @return codes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public List<Integer> getCodes() {
        return codes.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Integer>> getCodes_JsonNullable() {
    return codes;
  }
  
  @JsonProperty(JSON_PROPERTY_CODES)
  public void setCodes_JsonNullable(JsonNullable<List<Integer>> codes) {
    this.codes = codes;
  }

  public void setCodes(List<Integer> codes) {
    this.codes = JsonNullable.<List<Integer>>of(codes);
  }


  /**
   * Return true if this ChildAA_allOf object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChildAAAllOf childAAAllOf = (ChildAAAllOf) o;
    return Objects.equals(this.childAAAttribute, childAAAllOf.childAAAttribute) &&
        equalsNullable(this.sizedArray, childAAAllOf.sizedArray) &&
        Objects.equals(this.requiredArray, childAAAllOf.requiredArray) &&
        Objects.equals(this.bigIntegerCode, childAAAllOf.bigIntegerCode) &&
        Objects.equals(this.integerCode, childAAAllOf.integerCode) &&
        equalsNullable(this.codes, childAAAllOf.codes);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(childAAAttribute, hashCodeNullable(sizedArray), requiredArray, bigIntegerCode, integerCode, hashCodeNullable(codes));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChildAAAllOf {\n");
    sb.append("    childAAAttribute: ").append(toIndentedString(childAAAttribute)).append("\n");
    sb.append("    sizedArray: ").append(toIndentedString(sizedArray)).append("\n");
    sb.append("    requiredArray: ").append(toIndentedString(requiredArray)).append("\n");
    sb.append("    bigIntegerCode: ").append(toIndentedString(bigIntegerCode)).append("\n");
    sb.append("    integerCode: ").append(toIndentedString(integerCode)).append("\n");
    sb.append("    codes: ").append(toIndentedString(codes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

