/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import openapitools.model.BookingID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * ComplexBookingID
 */
@JsonPropertyOrder({
  ComplexBookingID.JSON_PROPERTY_REFERENCE_I_D,
  ComplexBookingID.JSON_PROPERTY_INTERNAL_I_D,
  ComplexBookingID.JSON_PROPERTY_BOOKING_I_DS,
  ComplexBookingID.JSON_PROPERTY_COMPLEX_BOOKING_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ComplexBookingID {
  public static final String JSON_PROPERTY_REFERENCE_I_D = "referenceID";
  private String referenceID;

  public static final String JSON_PROPERTY_INTERNAL_I_D = "internalID";
  private Long internalID;

  public static final String JSON_PROPERTY_BOOKING_I_DS = "bookingIDs";
  private List<BookingID> bookingIDs = new ArrayList<>();

  public static final String JSON_PROPERTY_COMPLEX_BOOKING_TYPE = "complexBookingType";
  private String complexBookingType;

  public ComplexBookingID() { 
  }

  public ComplexBookingID referenceID(String referenceID) {
    this.referenceID = referenceID;
    return this;
  }

   /**
   * Get referenceID
   * @return referenceID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_REFERENCE_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReferenceID() {
    return referenceID;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReferenceID(String referenceID) {
    this.referenceID = referenceID;
  }


  public ComplexBookingID internalID(Long internalID) {
    this.internalID = internalID;
    return this;
  }

   /**
   * Get internalID
   * @return internalID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_INTERNAL_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getInternalID() {
    return internalID;
  }


  @JsonProperty(JSON_PROPERTY_INTERNAL_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInternalID(Long internalID) {
    this.internalID = internalID;
  }


  public ComplexBookingID bookingIDs(List<BookingID> bookingIDs) {
    this.bookingIDs = bookingIDs;
    return this;
  }

  public ComplexBookingID addBookingIDsItem(BookingID bookingIDsItem) {
    this.bookingIDs.add(bookingIDsItem);
    return this;
  }

   /**
   * Get bookingIDs
   * @return bookingIDs
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BOOKING_I_DS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<BookingID> getBookingIDs() {
    return bookingIDs;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING_I_DS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBookingIDs(List<BookingID> bookingIDs) {
    this.bookingIDs = bookingIDs;
  }


  public ComplexBookingID complexBookingType(String complexBookingType) {
    this.complexBookingType = complexBookingType;
    return this;
  }

   /**
   * Get complexBookingType
   * @return complexBookingType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COMPLEX_BOOKING_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getComplexBookingType() {
    return complexBookingType;
  }


  @JsonProperty(JSON_PROPERTY_COMPLEX_BOOKING_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setComplexBookingType(String complexBookingType) {
    this.complexBookingType = complexBookingType;
  }


  /**
   * Return true if this ComplexBookingID object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComplexBookingID complexBookingID = (ComplexBookingID) o;
    return Objects.equals(this.referenceID, complexBookingID.referenceID) &&
        Objects.equals(this.internalID, complexBookingID.internalID) &&
        Objects.equals(this.bookingIDs, complexBookingID.bookingIDs) &&
        Objects.equals(this.complexBookingType, complexBookingID.complexBookingType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceID, internalID, bookingIDs, complexBookingType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComplexBookingID {\n");
    sb.append("    referenceID: ").append(toIndentedString(referenceID)).append("\n");
    sb.append("    internalID: ").append(toIndentedString(internalID)).append("\n");
    sb.append("    bookingIDs: ").append(toIndentedString(bookingIDs)).append("\n");
    sb.append("    complexBookingType: ").append(toIndentedString(complexBookingType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

