/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import openapitools.model.Message;
import openapitools.model.MyBusinessObject;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * DoSomethingResponse
 */
@JsonPropertyOrder({
  DoSomethingResponse.JSON_PROPERTY_ERRORS,
  DoSomethingResponse.JSON_PROPERTY_WARNINGS,
  DoSomethingResponse.JSON_PROPERTY_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class DoSomethingResponse {
  public static final String JSON_PROPERTY_ERRORS = "errors";
  @javax.annotation.Nullable
  private List<Message> errors = new ArrayList<>();

  public static final String JSON_PROPERTY_WARNINGS = "warnings";
  @javax.annotation.Nullable
  private List<Message> warnings = new ArrayList<>();

  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nonnull
  private MyBusinessObject value;

  public DoSomethingResponse() { 
  }

  public DoSomethingResponse errors(@javax.annotation.Nullable List<Message> errors) {
    this.errors = errors;
    return this;
  }

  public DoSomethingResponse addErrorsItem(Message errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Message> getErrors() {
    return errors;
  }


  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrors(@javax.annotation.Nullable List<Message> errors) {
    this.errors = errors;
  }


  public DoSomethingResponse warnings(@javax.annotation.Nullable List<Message> warnings) {
    this.warnings = warnings;
    return this;
  }

  public DoSomethingResponse addWarningsItem(Message warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

  /**
   * Get warnings
   * @return warnings
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WARNINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Message> getWarnings() {
    return warnings;
  }


  @JsonProperty(JSON_PROPERTY_WARNINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWarnings(@javax.annotation.Nullable List<Message> warnings) {
    this.warnings = warnings;
  }


  public DoSomethingResponse value(@javax.annotation.Nonnull MyBusinessObject value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MyBusinessObject getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue(@javax.annotation.Nonnull MyBusinessObject value) {
    this.value = value;
  }


  /**
   * Return true if this DoSomethingResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoSomethingResponse doSomethingResponse = (DoSomethingResponse) o;
    return Objects.equals(this.errors, doSomethingResponse.errors) &&
        Objects.equals(this.warnings, doSomethingResponse.warnings) &&
        Objects.equals(this.value, doSomethingResponse.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, warnings, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoSomethingResponse {\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

