/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * OpenAPITestObject
 */
@JsonPropertyOrder({
  OpenAPITestObject.JSON_PROPERTY_READ_ONLY_ATTRIBUTE,
  OpenAPITestObject.JSON_PROPERTY_READ_WRITE_ATTRIBUTE,
  OpenAPITestObject.JSON_PROPERTY_WRITE_ONLY_ATTRIBUTE,
  OpenAPITestObject.JSON_PROPERTY_NULLABLE_ATTRIBUTE,
  OpenAPITestObject.JSON_PROPERTY_NOT_NULLABLE_ATTRIBUTE,
  OpenAPITestObject.JSON_PROPERTY_READ_ONLY_ARRAY,
  OpenAPITestObject.JSON_PROPERTY_READ_WRITE_ARRAY,
  OpenAPITestObject.JSON_PROPERTY_WRITE_ONLY_ARRAY,
  OpenAPITestObject.JSON_PROPERTY_NULLABLE_ARRAY,
  OpenAPITestObject.JSON_PROPERTY_NOT_NULLABLE_ARRAY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OpenAPITestObject {
  public static final String JSON_PROPERTY_READ_ONLY_ATTRIBUTE = "readOnlyAttribute";
  private String readOnlyAttribute;

  public static final String JSON_PROPERTY_READ_WRITE_ATTRIBUTE = "readWriteAttribute";
  private String readWriteAttribute;

  public static final String JSON_PROPERTY_WRITE_ONLY_ATTRIBUTE = "writeOnlyAttribute";
  private Integer writeOnlyAttribute;

  public static final String JSON_PROPERTY_NULLABLE_ATTRIBUTE = "nullableAttribute";
  private Boolean nullableAttribute;

  public static final String JSON_PROPERTY_NOT_NULLABLE_ATTRIBUTE = "notNullableAttribute";
  private Double notNullableAttribute;

  public static final String JSON_PROPERTY_READ_ONLY_ARRAY = "readOnlyArray";
  private String readOnlyArray;

  public static final String JSON_PROPERTY_READ_WRITE_ARRAY = "readWriteArray";
  private String readWriteArray;

  public static final String JSON_PROPERTY_WRITE_ONLY_ARRAY = "writeOnlyArray";
  private Integer writeOnlyArray;

  public static final String JSON_PROPERTY_NULLABLE_ARRAY = "nullableArray";
  private Double nullableArray;

  public static final String JSON_PROPERTY_NOT_NULLABLE_ARRAY = "notNullableArray";
  private Double notNullableArray;

  public OpenAPITestObject() { 
  }

  public OpenAPITestObject readOnlyAttribute(String readOnlyAttribute) {
    this.readOnlyAttribute = readOnlyAttribute;
    return this;
  }

   /**
   * Get readOnlyAttribute
   * @return readOnlyAttribute
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_ONLY_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReadOnlyAttribute() {
    return readOnlyAttribute;
  }


  @JsonProperty(JSON_PROPERTY_READ_ONLY_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReadOnlyAttribute(String readOnlyAttribute) {
    this.readOnlyAttribute = readOnlyAttribute;
  }


  public OpenAPITestObject readWriteAttribute(String readWriteAttribute) {
    this.readWriteAttribute = readWriteAttribute;
    return this;
  }

   /**
   * Get readWriteAttribute
   * @return readWriteAttribute
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_WRITE_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReadWriteAttribute() {
    return readWriteAttribute;
  }


  @JsonProperty(JSON_PROPERTY_READ_WRITE_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReadWriteAttribute(String readWriteAttribute) {
    this.readWriteAttribute = readWriteAttribute;
  }


  public OpenAPITestObject writeOnlyAttribute(Integer writeOnlyAttribute) {
    this.writeOnlyAttribute = writeOnlyAttribute;
    return this;
  }

   /**
   * Get writeOnlyAttribute
   * @return writeOnlyAttribute
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WRITE_ONLY_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getWriteOnlyAttribute() {
    return writeOnlyAttribute;
  }


  @JsonProperty(JSON_PROPERTY_WRITE_ONLY_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWriteOnlyAttribute(Integer writeOnlyAttribute) {
    this.writeOnlyAttribute = writeOnlyAttribute;
  }


  public OpenAPITestObject nullableAttribute(Boolean nullableAttribute) {
    this.nullableAttribute = nullableAttribute;
    return this;
  }

   /**
   * Get nullableAttribute
   * @return nullableAttribute
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NULLABLE_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getNullableAttribute() {
    return nullableAttribute;
  }


  @JsonProperty(JSON_PROPERTY_NULLABLE_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNullableAttribute(Boolean nullableAttribute) {
    this.nullableAttribute = nullableAttribute;
  }


  public OpenAPITestObject notNullableAttribute(Double notNullableAttribute) {
    this.notNullableAttribute = notNullableAttribute;
    return this;
  }

   /**
   * Get notNullableAttribute
   * @return notNullableAttribute
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NOT_NULLABLE_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getNotNullableAttribute() {
    return notNullableAttribute;
  }


  @JsonProperty(JSON_PROPERTY_NOT_NULLABLE_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNotNullableAttribute(Double notNullableAttribute) {
    this.notNullableAttribute = notNullableAttribute;
  }


  public OpenAPITestObject readOnlyArray(String readOnlyArray) {
    this.readOnlyArray = readOnlyArray;
    return this;
  }

   /**
   * Get readOnlyArray
   * @return readOnlyArray
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_ONLY_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReadOnlyArray() {
    return readOnlyArray;
  }


  @JsonProperty(JSON_PROPERTY_READ_ONLY_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReadOnlyArray(String readOnlyArray) {
    this.readOnlyArray = readOnlyArray;
  }


  public OpenAPITestObject readWriteArray(String readWriteArray) {
    this.readWriteArray = readWriteArray;
    return this;
  }

   /**
   * Get readWriteArray
   * @return readWriteArray
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_WRITE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReadWriteArray() {
    return readWriteArray;
  }


  @JsonProperty(JSON_PROPERTY_READ_WRITE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReadWriteArray(String readWriteArray) {
    this.readWriteArray = readWriteArray;
  }


  public OpenAPITestObject writeOnlyArray(Integer writeOnlyArray) {
    this.writeOnlyArray = writeOnlyArray;
    return this;
  }

   /**
   * Get writeOnlyArray
   * @return writeOnlyArray
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WRITE_ONLY_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getWriteOnlyArray() {
    return writeOnlyArray;
  }


  @JsonProperty(JSON_PROPERTY_WRITE_ONLY_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWriteOnlyArray(Integer writeOnlyArray) {
    this.writeOnlyArray = writeOnlyArray;
  }


  public OpenAPITestObject nullableArray(Double nullableArray) {
    this.nullableArray = nullableArray;
    return this;
  }

   /**
   * Get nullableArray
   * @return nullableArray
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NULLABLE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getNullableArray() {
    return nullableArray;
  }


  @JsonProperty(JSON_PROPERTY_NULLABLE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNullableArray(Double nullableArray) {
    this.nullableArray = nullableArray;
  }


  public OpenAPITestObject notNullableArray(Double notNullableArray) {
    this.notNullableArray = notNullableArray;
    return this;
  }

   /**
   * Get notNullableArray
   * @return notNullableArray
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NOT_NULLABLE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getNotNullableArray() {
    return notNullableArray;
  }


  @JsonProperty(JSON_PROPERTY_NOT_NULLABLE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNotNullableArray(Double notNullableArray) {
    this.notNullableArray = notNullableArray;
  }


  /**
   * Return true if this OpenAPITestObject object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenAPITestObject openAPITestObject = (OpenAPITestObject) o;
    return Objects.equals(this.readOnlyAttribute, openAPITestObject.readOnlyAttribute) &&
        Objects.equals(this.readWriteAttribute, openAPITestObject.readWriteAttribute) &&
        Objects.equals(this.writeOnlyAttribute, openAPITestObject.writeOnlyAttribute) &&
        Objects.equals(this.nullableAttribute, openAPITestObject.nullableAttribute) &&
        Objects.equals(this.notNullableAttribute, openAPITestObject.notNullableAttribute) &&
        Objects.equals(this.readOnlyArray, openAPITestObject.readOnlyArray) &&
        Objects.equals(this.readWriteArray, openAPITestObject.readWriteArray) &&
        Objects.equals(this.writeOnlyArray, openAPITestObject.writeOnlyArray) &&
        Objects.equals(this.nullableArray, openAPITestObject.nullableArray) &&
        Objects.equals(this.notNullableArray, openAPITestObject.notNullableArray);
  }

  @Override
  public int hashCode() {
    return Objects.hash(readOnlyAttribute, readWriteAttribute, writeOnlyAttribute, nullableAttribute, notNullableAttribute, readOnlyArray, readWriteArray, writeOnlyArray, nullableArray, notNullableArray);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenAPITestObject {\n");
    sb.append("    readOnlyAttribute: ").append(toIndentedString(readOnlyAttribute)).append("\n");
    sb.append("    readWriteAttribute: ").append(toIndentedString(readWriteAttribute)).append("\n");
    sb.append("    writeOnlyAttribute: ").append(toIndentedString(writeOnlyAttribute)).append("\n");
    sb.append("    nullableAttribute: ").append(toIndentedString(nullableAttribute)).append("\n");
    sb.append("    notNullableAttribute: ").append(toIndentedString(notNullableAttribute)).append("\n");
    sb.append("    readOnlyArray: ").append(toIndentedString(readOnlyArray)).append("\n");
    sb.append("    readWriteArray: ").append(toIndentedString(readWriteArray)).append("\n");
    sb.append("    writeOnlyArray: ").append(toIndentedString(writeOnlyArray)).append("\n");
    sb.append("    nullableArray: ").append(toIndentedString(nullableArray)).append("\n");
    sb.append("    notNullableArray: ").append(toIndentedString(notNullableArray)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

