/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import openapitools.model.Partner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * PartnerContainer
 */
@JsonPropertyOrder({
  PartnerContainer.JSON_PROPERTY_PARTNERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PartnerContainer {
  public static final String JSON_PROPERTY_PARTNERS = "partners";
  private List<Partner> partners = null;

  public PartnerContainer() { 
  }

  public PartnerContainer partners(List<Partner> partners) {
    this.partners = partners;
    return this;
  }

  public PartnerContainer addPartnersItem(Partner partnersItem) {
    if (this.partners == null) {
      this.partners = new ArrayList<>();
    }
    this.partners.add(partnersItem);
    return this;
  }

   /**
   * Get partners
   * @return partners
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARTNERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Partner> getPartners() {
    return partners;
  }


  @JsonProperty(JSON_PROPERTY_PARTNERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPartners(List<Partner> partners) {
    this.partners = partners;
  }


  /**
   * Return true if this PartnerContainer object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartnerContainer partnerContainer = (PartnerContainer) o;
    return Objects.equals(this.partners, partnerContainer.partners);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partners);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartnerContainer {\n");
    sb.append("    partners: ").append(toIndentedString(partners)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

