/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import openapitools.model.PostalAddress;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * Partner
 */
@JsonPropertyOrder({
  Partner.JSON_PROPERTY_OBJECT_TYPE,
  Partner.JSON_PROPERTY_POSTAL_ADDRESSES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
@JsonIgnoreProperties(
  value = "objectType", // ignore manually set objectType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the objectType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "objectType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Company.class, name = "Company"),
  @JsonSubTypes.Type(value = Person.class, name = "Person"),
})

public class Partner {
  public static final String JSON_PROPERTY_OBJECT_TYPE = "objectType";
  @javax.annotation.Nonnull
  private String objectType;

  public static final String JSON_PROPERTY_POSTAL_ADDRESSES = "postalAddresses";
  @javax.annotation.Nullable
  private List<PostalAddress> postalAddresses = new ArrayList<>();

  public Partner() { 
  }

  public Partner objectType(@javax.annotation.Nonnull String objectType) {
    this.objectType = objectType;
    return this;
  }

  /**
   * Attribute is used as discriminator for inheritance between data types.
   * @return objectType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OBJECT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getObjectType() {
    return objectType;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObjectType(@javax.annotation.Nonnull String objectType) {
    this.objectType = objectType;
  }


  public Partner postalAddresses(@javax.annotation.Nullable List<PostalAddress> postalAddresses) {
    this.postalAddresses = postalAddresses;
    return this;
  }

  public Partner addPostalAddressesItem(PostalAddress postalAddressesItem) {
    if (this.postalAddresses == null) {
      this.postalAddresses = new ArrayList<>();
    }
    this.postalAddresses.add(postalAddressesItem);
    return this;
  }

  /**
   * Get postalAddresses
   * @return postalAddresses
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POSTAL_ADDRESSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PostalAddress> getPostalAddresses() {
    return postalAddresses;
  }


  @JsonProperty(value = JSON_PROPERTY_POSTAL_ADDRESSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostalAddresses(@javax.annotation.Nullable List<PostalAddress> postalAddresses) {
    this.postalAddresses = postalAddresses;
  }


  /**
   * Return true if this Partner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Partner partner = (Partner) o;
    return Objects.equals(this.objectType, partner.objectType) &&
        Objects.equals(this.postalAddresses, partner.postalAddresses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectType, postalAddresses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Partner {\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    postalAddresses: ").append(toIndentedString(postalAddresses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  static {
    // Initialize and register the discriminator mappings.
    Map<String, Class<?>> mappings = new HashMap<>();
    mappings.put("Company", Company.class);
    mappings.put("Person", Person.class);
    mappings.put("Partner", Partner.class);
    JSON.registerDiscriminator(Partner.class, "objectType", mappings);
  }
}

