/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * PrimitiveObjectWithRestrictions
 */
@JsonPropertyOrder({
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_A_BOOLEAN,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_B_BOOLEAN,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_C_BOOLEAN,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_A_BYTE,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_B_BYTE,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_A_SHORT,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_B_SHORT,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_A_INTEGER,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_B_INTEGER,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_C_INTEGER,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_A_LONG,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_B_LONG,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_A_BIG_INTEGER,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_A_CHARACTER,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_B_CHARACTER,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_A_FLOAT,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_B_FLOAT,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_A_DOUBLE,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_B_DOUBLE,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_A_BIG_DECIMAL,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_A_STRING,
  PrimitiveObjectWithRestrictions.JSON_PROPERTY_B_STRING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class PrimitiveObjectWithRestrictions {
  public static final String JSON_PROPERTY_A_BOOLEAN = "aBoolean";
  @javax.annotation.Nonnull
  private Boolean aBoolean = true;

  public static final String JSON_PROPERTY_B_BOOLEAN = "bBoolean";
  @javax.annotation.Nonnull
  private Boolean bBoolean;

  public static final String JSON_PROPERTY_C_BOOLEAN = "cBoolean";
  @javax.annotation.Nonnull
  private Boolean cBoolean;

  public static final String JSON_PROPERTY_A_BYTE = "aByte";
  @javax.annotation.Nonnull
  private Integer aByte;

  public static final String JSON_PROPERTY_B_BYTE = "bByte";
  @javax.annotation.Nonnull
  private Integer bByte;

  public static final String JSON_PROPERTY_A_SHORT = "aShort";
  @javax.annotation.Nonnull
  private Integer aShort;

  public static final String JSON_PROPERTY_B_SHORT = "bShort";
  @javax.annotation.Nonnull
  private Integer bShort;

  public static final String JSON_PROPERTY_A_INTEGER = "aInteger";
  @javax.annotation.Nonnull
  private Integer aInteger;

  public static final String JSON_PROPERTY_B_INTEGER = "bInteger";
  @javax.annotation.Nonnull
  private Integer bInteger;

  public static final String JSON_PROPERTY_C_INTEGER = "cInteger";
  @javax.annotation.Nonnull
  private Integer cInteger;

  public static final String JSON_PROPERTY_A_LONG = "aLong";
  @javax.annotation.Nonnull
  private Long aLong;

  public static final String JSON_PROPERTY_B_LONG = "bLong";
  @javax.annotation.Nonnull
  private Long bLong;

  public static final String JSON_PROPERTY_A_BIG_INTEGER = "aBigInteger";
  @javax.annotation.Nonnull
  private Long aBigInteger;

  public static final String JSON_PROPERTY_A_CHARACTER = "aCharacter";
  @javax.annotation.Nonnull
  private String aCharacter;

  public static final String JSON_PROPERTY_B_CHARACTER = "bCharacter";
  @javax.annotation.Nonnull
  private String bCharacter;

  public static final String JSON_PROPERTY_A_FLOAT = "aFloat";
  @javax.annotation.Nonnull
  private Float aFloat;

  public static final String JSON_PROPERTY_B_FLOAT = "bFloat";
  @javax.annotation.Nonnull
  private Float bFloat;

  public static final String JSON_PROPERTY_A_DOUBLE = "aDouble";
  @javax.annotation.Nonnull
  private Double aDouble = 42.0d;

  public static final String JSON_PROPERTY_B_DOUBLE = "bDouble";
  @javax.annotation.Nonnull
  private Double bDouble;

  public static final String JSON_PROPERTY_A_BIG_DECIMAL = "aBigDecimal";
  @javax.annotation.Nonnull
  private Double aBigDecimal;

  public static final String JSON_PROPERTY_A_STRING = "aString";
  @javax.annotation.Nonnull
  private String aString = "Hello OpenAPI";

  public static final String JSON_PROPERTY_B_STRING = "bString";
  @javax.annotation.Nonnull
  private String bString;

  public PrimitiveObjectWithRestrictions() { 
  }

  public PrimitiveObjectWithRestrictions aBoolean(@javax.annotation.Nonnull Boolean aBoolean) {
    this.aBoolean = aBoolean;
    return this;
  }

  /**
   * Get aBoolean
   * @return aBoolean
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_A_BOOLEAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getaBoolean() {
    return aBoolean;
  }


  @JsonProperty(JSON_PROPERTY_A_BOOLEAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setaBoolean(@javax.annotation.Nonnull Boolean aBoolean) {
    this.aBoolean = aBoolean;
  }


  public PrimitiveObjectWithRestrictions bBoolean(@javax.annotation.Nonnull Boolean bBoolean) {
    this.bBoolean = bBoolean;
    return this;
  }

  /**
   * Get bBoolean
   * @return bBoolean
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_B_BOOLEAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getbBoolean() {
    return bBoolean;
  }


  @JsonProperty(JSON_PROPERTY_B_BOOLEAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setbBoolean(@javax.annotation.Nonnull Boolean bBoolean) {
    this.bBoolean = bBoolean;
  }


  public PrimitiveObjectWithRestrictions cBoolean(@javax.annotation.Nonnull Boolean cBoolean) {
    this.cBoolean = cBoolean;
    return this;
  }

  /**
   * Get cBoolean
   * @return cBoolean
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_C_BOOLEAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getcBoolean() {
    return cBoolean;
  }


  @JsonProperty(JSON_PROPERTY_C_BOOLEAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setcBoolean(@javax.annotation.Nonnull Boolean cBoolean) {
    this.cBoolean = cBoolean;
  }


  public PrimitiveObjectWithRestrictions aByte(@javax.annotation.Nonnull Integer aByte) {
    this.aByte = aByte;
    return this;
  }

  /**
   * Get aByte
   * maximum: 0
   * @return aByte
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_A_BYTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getaByte() {
    return aByte;
  }


  @JsonProperty(JSON_PROPERTY_A_BYTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setaByte(@javax.annotation.Nonnull Integer aByte) {
    this.aByte = aByte;
  }


  public PrimitiveObjectWithRestrictions bByte(@javax.annotation.Nonnull Integer bByte) {
    this.bByte = bByte;
    return this;
  }

  /**
   * Get bByte
   * maximum: 0
   * @return bByte
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_B_BYTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getbByte() {
    return bByte;
  }


  @JsonProperty(JSON_PROPERTY_B_BYTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setbByte(@javax.annotation.Nonnull Integer bByte) {
    this.bByte = bByte;
  }


  public PrimitiveObjectWithRestrictions aShort(@javax.annotation.Nonnull Integer aShort) {
    this.aShort = aShort;
    return this;
  }

  /**
   * Get aShort
   * minimum: -237
   * @return aShort
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_A_SHORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getaShort() {
    return aShort;
  }


  @JsonProperty(JSON_PROPERTY_A_SHORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setaShort(@javax.annotation.Nonnull Integer aShort) {
    this.aShort = aShort;
  }


  public PrimitiveObjectWithRestrictions bShort(@javax.annotation.Nonnull Integer bShort) {
    this.bShort = bShort;
    return this;
  }

  /**
   * Get bShort
   * minimum: 0
   * @return bShort
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_B_SHORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getbShort() {
    return bShort;
  }


  @JsonProperty(JSON_PROPERTY_B_SHORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setbShort(@javax.annotation.Nonnull Integer bShort) {
    this.bShort = bShort;
  }


  public PrimitiveObjectWithRestrictions aInteger(@javax.annotation.Nonnull Integer aInteger) {
    this.aInteger = aInteger;
    return this;
  }

  /**
   * Get aInteger
   * minimum: 0
   * @return aInteger
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_A_INTEGER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getaInteger() {
    return aInteger;
  }


  @JsonProperty(JSON_PROPERTY_A_INTEGER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setaInteger(@javax.annotation.Nonnull Integer aInteger) {
    this.aInteger = aInteger;
  }


  public PrimitiveObjectWithRestrictions bInteger(@javax.annotation.Nonnull Integer bInteger) {
    this.bInteger = bInteger;
    return this;
  }

  /**
   * Get bInteger
   * minimum: 4711
   * @return bInteger
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_B_INTEGER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getbInteger() {
    return bInteger;
  }


  @JsonProperty(JSON_PROPERTY_B_INTEGER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setbInteger(@javax.annotation.Nonnull Integer bInteger) {
    this.bInteger = bInteger;
  }


  public PrimitiveObjectWithRestrictions cInteger(@javax.annotation.Nonnull Integer cInteger) {
    this.cInteger = cInteger;
    return this;
  }

  /**
   * Get cInteger
   * minimum: 100
   * maximum: 1000
   * @return cInteger
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_C_INTEGER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getcInteger() {
    return cInteger;
  }


  @JsonProperty(JSON_PROPERTY_C_INTEGER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setcInteger(@javax.annotation.Nonnull Integer cInteger) {
    this.cInteger = cInteger;
  }


  public PrimitiveObjectWithRestrictions aLong(@javax.annotation.Nonnull Long aLong) {
    this.aLong = aLong;
    return this;
  }

  /**
   * Get aLong
   * @return aLong
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_A_LONG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getaLong() {
    return aLong;
  }


  @JsonProperty(JSON_PROPERTY_A_LONG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setaLong(@javax.annotation.Nonnull Long aLong) {
    this.aLong = aLong;
  }


  public PrimitiveObjectWithRestrictions bLong(@javax.annotation.Nonnull Long bLong) {
    this.bLong = bLong;
    return this;
  }

  /**
   * Get bLong
   * maximum: 299792458
   * @return bLong
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_B_LONG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getbLong() {
    return bLong;
  }


  @JsonProperty(JSON_PROPERTY_B_LONG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setbLong(@javax.annotation.Nonnull Long bLong) {
    this.bLong = bLong;
  }


  public PrimitiveObjectWithRestrictions aBigInteger(@javax.annotation.Nonnull Long aBigInteger) {
    this.aBigInteger = aBigInteger;
    return this;
  }

  /**
   * Get aBigInteger
   * minimum: -3
   * maximum: 3
   * @return aBigInteger
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_A_BIG_INTEGER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getaBigInteger() {
    return aBigInteger;
  }


  @JsonProperty(JSON_PROPERTY_A_BIG_INTEGER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setaBigInteger(@javax.annotation.Nonnull Long aBigInteger) {
    this.aBigInteger = aBigInteger;
  }


  public PrimitiveObjectWithRestrictions aCharacter(@javax.annotation.Nonnull String aCharacter) {
    this.aCharacter = aCharacter;
    return this;
  }

  /**
   * Get aCharacter
   * @return aCharacter
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_A_CHARACTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getaCharacter() {
    return aCharacter;
  }


  @JsonProperty(JSON_PROPERTY_A_CHARACTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setaCharacter(@javax.annotation.Nonnull String aCharacter) {
    this.aCharacter = aCharacter;
  }


  public PrimitiveObjectWithRestrictions bCharacter(@javax.annotation.Nonnull String bCharacter) {
    this.bCharacter = bCharacter;
    return this;
  }

  /**
   * Get bCharacter
   * @return bCharacter
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_B_CHARACTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getbCharacter() {
    return bCharacter;
  }


  @JsonProperty(JSON_PROPERTY_B_CHARACTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setbCharacter(@javax.annotation.Nonnull String bCharacter) {
    this.bCharacter = bCharacter;
  }


  public PrimitiveObjectWithRestrictions aFloat(@javax.annotation.Nonnull Float aFloat) {
    this.aFloat = aFloat;
    return this;
  }

  /**
   * Get aFloat
   * @return aFloat
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_A_FLOAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Float getaFloat() {
    return aFloat;
  }


  @JsonProperty(JSON_PROPERTY_A_FLOAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setaFloat(@javax.annotation.Nonnull Float aFloat) {
    this.aFloat = aFloat;
  }


  public PrimitiveObjectWithRestrictions bFloat(@javax.annotation.Nonnull Float bFloat) {
    this.bFloat = bFloat;
    return this;
  }

  /**
   * Get bFloat
   * @return bFloat
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_B_FLOAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Float getbFloat() {
    return bFloat;
  }


  @JsonProperty(JSON_PROPERTY_B_FLOAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setbFloat(@javax.annotation.Nonnull Float bFloat) {
    this.bFloat = bFloat;
  }


  public PrimitiveObjectWithRestrictions aDouble(@javax.annotation.Nonnull Double aDouble) {
    this.aDouble = aDouble;
    return this;
  }

  /**
   * Get aDouble
   * @return aDouble
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_A_DOUBLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getaDouble() {
    return aDouble;
  }


  @JsonProperty(JSON_PROPERTY_A_DOUBLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setaDouble(@javax.annotation.Nonnull Double aDouble) {
    this.aDouble = aDouble;
  }


  public PrimitiveObjectWithRestrictions bDouble(@javax.annotation.Nonnull Double bDouble) {
    this.bDouble = bDouble;
    return this;
  }

  /**
   * Get bDouble
   * @return bDouble
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_B_DOUBLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getbDouble() {
    return bDouble;
  }


  @JsonProperty(JSON_PROPERTY_B_DOUBLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setbDouble(@javax.annotation.Nonnull Double bDouble) {
    this.bDouble = bDouble;
  }


  public PrimitiveObjectWithRestrictions aBigDecimal(@javax.annotation.Nonnull Double aBigDecimal) {
    this.aBigDecimal = aBigDecimal;
    return this;
  }

  /**
   * Get aBigDecimal
   * minimum: 4711.0815
   * @return aBigDecimal
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_A_BIG_DECIMAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getaBigDecimal() {
    return aBigDecimal;
  }


  @JsonProperty(JSON_PROPERTY_A_BIG_DECIMAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setaBigDecimal(@javax.annotation.Nonnull Double aBigDecimal) {
    this.aBigDecimal = aBigDecimal;
  }


  public PrimitiveObjectWithRestrictions aString(@javax.annotation.Nonnull String aString) {
    this.aString = aString;
    return this;
  }

  /**
   * Get aString
   * @return aString
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_A_STRING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getaString() {
    return aString;
  }


  @JsonProperty(JSON_PROPERTY_A_STRING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setaString(@javax.annotation.Nonnull String aString) {
    this.aString = aString;
  }


  public PrimitiveObjectWithRestrictions bString(@javax.annotation.Nonnull String bString) {
    this.bString = bString;
    return this;
  }

  /**
   * Get bString
   * @return bString
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_B_STRING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getbString() {
    return bString;
  }


  @JsonProperty(JSON_PROPERTY_B_STRING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setbString(@javax.annotation.Nonnull String bString) {
    this.bString = bString;
  }


  /**
   * Return true if this PrimitiveObjectWithRestrictions object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrimitiveObjectWithRestrictions primitiveObjectWithRestrictions = (PrimitiveObjectWithRestrictions) o;
    return Objects.equals(this.aBoolean, primitiveObjectWithRestrictions.aBoolean) &&
        Objects.equals(this.bBoolean, primitiveObjectWithRestrictions.bBoolean) &&
        Objects.equals(this.cBoolean, primitiveObjectWithRestrictions.cBoolean) &&
        Objects.equals(this.aByte, primitiveObjectWithRestrictions.aByte) &&
        Objects.equals(this.bByte, primitiveObjectWithRestrictions.bByte) &&
        Objects.equals(this.aShort, primitiveObjectWithRestrictions.aShort) &&
        Objects.equals(this.bShort, primitiveObjectWithRestrictions.bShort) &&
        Objects.equals(this.aInteger, primitiveObjectWithRestrictions.aInteger) &&
        Objects.equals(this.bInteger, primitiveObjectWithRestrictions.bInteger) &&
        Objects.equals(this.cInteger, primitiveObjectWithRestrictions.cInteger) &&
        Objects.equals(this.aLong, primitiveObjectWithRestrictions.aLong) &&
        Objects.equals(this.bLong, primitiveObjectWithRestrictions.bLong) &&
        Objects.equals(this.aBigInteger, primitiveObjectWithRestrictions.aBigInteger) &&
        Objects.equals(this.aCharacter, primitiveObjectWithRestrictions.aCharacter) &&
        Objects.equals(this.bCharacter, primitiveObjectWithRestrictions.bCharacter) &&
        Objects.equals(this.aFloat, primitiveObjectWithRestrictions.aFloat) &&
        Objects.equals(this.bFloat, primitiveObjectWithRestrictions.bFloat) &&
        Objects.equals(this.aDouble, primitiveObjectWithRestrictions.aDouble) &&
        Objects.equals(this.bDouble, primitiveObjectWithRestrictions.bDouble) &&
        Objects.equals(this.aBigDecimal, primitiveObjectWithRestrictions.aBigDecimal) &&
        Objects.equals(this.aString, primitiveObjectWithRestrictions.aString) &&
        Objects.equals(this.bString, primitiveObjectWithRestrictions.bString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aBoolean, bBoolean, cBoolean, aByte, bByte, aShort, bShort, aInteger, bInteger, cInteger, aLong, bLong, aBigInteger, aCharacter, bCharacter, aFloat, bFloat, aDouble, bDouble, aBigDecimal, aString, bString);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrimitiveObjectWithRestrictions {\n");
    sb.append("    aBoolean: ").append(toIndentedString(aBoolean)).append("\n");
    sb.append("    bBoolean: ").append(toIndentedString(bBoolean)).append("\n");
    sb.append("    cBoolean: ").append(toIndentedString(cBoolean)).append("\n");
    sb.append("    aByte: ").append(toIndentedString(aByte)).append("\n");
    sb.append("    bByte: ").append(toIndentedString(bByte)).append("\n");
    sb.append("    aShort: ").append(toIndentedString(aShort)).append("\n");
    sb.append("    bShort: ").append(toIndentedString(bShort)).append("\n");
    sb.append("    aInteger: ").append(toIndentedString(aInteger)).append("\n");
    sb.append("    bInteger: ").append(toIndentedString(bInteger)).append("\n");
    sb.append("    cInteger: ").append(toIndentedString(cInteger)).append("\n");
    sb.append("    aLong: ").append(toIndentedString(aLong)).append("\n");
    sb.append("    bLong: ").append(toIndentedString(bLong)).append("\n");
    sb.append("    aBigInteger: ").append(toIndentedString(aBigInteger)).append("\n");
    sb.append("    aCharacter: ").append(toIndentedString(aCharacter)).append("\n");
    sb.append("    bCharacter: ").append(toIndentedString(bCharacter)).append("\n");
    sb.append("    aFloat: ").append(toIndentedString(aFloat)).append("\n");
    sb.append("    bFloat: ").append(toIndentedString(bFloat)).append("\n");
    sb.append("    aDouble: ").append(toIndentedString(aDouble)).append("\n");
    sb.append("    bDouble: ").append(toIndentedString(bDouble)).append("\n");
    sb.append("    aBigDecimal: ").append(toIndentedString(aBigDecimal)).append("\n");
    sb.append("    aString: ").append(toIndentedString(aString)).append("\n");
    sb.append("    bString: ").append(toIndentedString(bString)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

