/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * PrimitiveArraysObjectWithRestrictions
 */
@JsonPropertyOrder({
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_A_BOOLEAN_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_B_BOOLEAN_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_C_BOOLEAN_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_A_BYTE_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_B_BYTE_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_A_SHORT_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_B_SHORT_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_A_INTEGER_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_B_INTEGER_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_C_INTEGER_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_A_LONG_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_B_LONG_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_A_BIG_INTEGER_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_A_CHARACTER_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_B_CHARACTER_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_A_FLOAT_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_B_FLOAT_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_A_DOUBLE_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_B_DOUBLE_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_A_BIG_DECIMAL_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_A_STRING_ARRAY,
  PrimitiveArraysObjectWithRestrictions.JSON_PROPERTY_B_STRING_ARRAY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PrimitiveArraysObjectWithRestrictions {
  public static final String JSON_PROPERTY_A_BOOLEAN_ARRAY = "aBooleanArray";
  private List<Boolean> aBooleanArray = null;

  public static final String JSON_PROPERTY_B_BOOLEAN_ARRAY = "bBooleanArray";
  private List<Boolean> bBooleanArray = null;

  public static final String JSON_PROPERTY_C_BOOLEAN_ARRAY = "cBooleanArray";
  private List<Boolean> cBooleanArray = null;

  public static final String JSON_PROPERTY_A_BYTE_ARRAY = "aByteArray";
  private byte[] aByteArray;

  public static final String JSON_PROPERTY_B_BYTE_ARRAY = "bByteArray";
  private byte[] bByteArray;

  public static final String JSON_PROPERTY_A_SHORT_ARRAY = "aShortArray";
  private List<Integer> aShortArray = null;

  public static final String JSON_PROPERTY_B_SHORT_ARRAY = "bShortArray";
  private List<Integer> bShortArray = null;

  public static final String JSON_PROPERTY_A_INTEGER_ARRAY = "aIntegerArray";
  private List<Integer> aIntegerArray = null;

  public static final String JSON_PROPERTY_B_INTEGER_ARRAY = "bIntegerArray";
  private List<Integer> bIntegerArray = null;

  public static final String JSON_PROPERTY_C_INTEGER_ARRAY = "cIntegerArray";
  private List<Integer> cIntegerArray = null;

  public static final String JSON_PROPERTY_A_LONG_ARRAY = "aLongArray";
  private List<Long> aLongArray = new ArrayList<>();

  public static final String JSON_PROPERTY_B_LONG_ARRAY = "bLongArray";
  private List<Long> bLongArray = null;

  public static final String JSON_PROPERTY_A_BIG_INTEGER_ARRAY = "aBigIntegerArray";
  private List<Long> aBigIntegerArray = null;

  public static final String JSON_PROPERTY_A_CHARACTER_ARRAY = "aCharacterArray";
  private List<String> aCharacterArray = null;

  public static final String JSON_PROPERTY_B_CHARACTER_ARRAY = "bCharacterArray";
  private List<String> bCharacterArray = null;

  public static final String JSON_PROPERTY_A_FLOAT_ARRAY = "aFloatArray";
  private List<Float> aFloatArray = null;

  public static final String JSON_PROPERTY_B_FLOAT_ARRAY = "bFloatArray";
  private List<Float> bFloatArray = null;

  public static final String JSON_PROPERTY_A_DOUBLE_ARRAY = "aDoubleArray";
  private List<Double> aDoubleArray = null;

  public static final String JSON_PROPERTY_B_DOUBLE_ARRAY = "bDoubleArray";
  private List<Double> bDoubleArray = null;

  public static final String JSON_PROPERTY_A_BIG_DECIMAL_ARRAY = "aBigDecimalArray";
  private List<Double> aBigDecimalArray = null;

  public static final String JSON_PROPERTY_A_STRING_ARRAY = "aStringArray";
  private List<String> aStringArray = null;

  public static final String JSON_PROPERTY_B_STRING_ARRAY = "bStringArray";
  private List<String> bStringArray = null;

  public PrimitiveArraysObjectWithRestrictions() { 
  }

  public PrimitiveArraysObjectWithRestrictions aBooleanArray(List<Boolean> aBooleanArray) {
    this.aBooleanArray = aBooleanArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addABooleanArrayItem(Boolean aBooleanArrayItem) {
    if (this.aBooleanArray == null) {
      this.aBooleanArray = new ArrayList<>();
    }
    this.aBooleanArray.add(aBooleanArrayItem);
    return this;
  }

   /**
   * Get aBooleanArray
   * @return aBooleanArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_BOOLEAN_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Boolean> getaBooleanArray() {
    return aBooleanArray;
  }


  @JsonProperty(JSON_PROPERTY_A_BOOLEAN_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaBooleanArray(List<Boolean> aBooleanArray) {
    this.aBooleanArray = aBooleanArray;
  }


  public PrimitiveArraysObjectWithRestrictions bBooleanArray(List<Boolean> bBooleanArray) {
    this.bBooleanArray = bBooleanArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addBBooleanArrayItem(Boolean bBooleanArrayItem) {
    if (this.bBooleanArray == null) {
      this.bBooleanArray = new ArrayList<>();
    }
    this.bBooleanArray.add(bBooleanArrayItem);
    return this;
  }

   /**
   * Get bBooleanArray
   * @return bBooleanArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_BOOLEAN_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Boolean> getbBooleanArray() {
    return bBooleanArray;
  }


  @JsonProperty(JSON_PROPERTY_B_BOOLEAN_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbBooleanArray(List<Boolean> bBooleanArray) {
    this.bBooleanArray = bBooleanArray;
  }


  public PrimitiveArraysObjectWithRestrictions cBooleanArray(List<Boolean> cBooleanArray) {
    this.cBooleanArray = cBooleanArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addCBooleanArrayItem(Boolean cBooleanArrayItem) {
    if (this.cBooleanArray == null) {
      this.cBooleanArray = new ArrayList<>();
    }
    this.cBooleanArray.add(cBooleanArrayItem);
    return this;
  }

   /**
   * Get cBooleanArray
   * @return cBooleanArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_C_BOOLEAN_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Boolean> getcBooleanArray() {
    return cBooleanArray;
  }


  @JsonProperty(JSON_PROPERTY_C_BOOLEAN_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcBooleanArray(List<Boolean> cBooleanArray) {
    this.cBooleanArray = cBooleanArray;
  }


  public PrimitiveArraysObjectWithRestrictions aByteArray(byte[] aByteArray) {
    this.aByteArray = aByteArray;
    return this;
  }

   /**
   * Get aByteArray
   * @return aByteArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_BYTE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getaByteArray() {
    return aByteArray;
  }


  @JsonProperty(JSON_PROPERTY_A_BYTE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaByteArray(byte[] aByteArray) {
    this.aByteArray = aByteArray;
  }


  public PrimitiveArraysObjectWithRestrictions bByteArray(byte[] bByteArray) {
    this.bByteArray = bByteArray;
    return this;
  }

   /**
   * Get bByteArray
   * @return bByteArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_BYTE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getbByteArray() {
    return bByteArray;
  }


  @JsonProperty(JSON_PROPERTY_B_BYTE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbByteArray(byte[] bByteArray) {
    this.bByteArray = bByteArray;
  }


  public PrimitiveArraysObjectWithRestrictions aShortArray(List<Integer> aShortArray) {
    this.aShortArray = aShortArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addAShortArrayItem(Integer aShortArrayItem) {
    if (this.aShortArray == null) {
      this.aShortArray = new ArrayList<>();
    }
    this.aShortArray.add(aShortArrayItem);
    return this;
  }

   /**
   * Get aShortArray
   * @return aShortArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_SHORT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getaShortArray() {
    return aShortArray;
  }


  @JsonProperty(JSON_PROPERTY_A_SHORT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaShortArray(List<Integer> aShortArray) {
    this.aShortArray = aShortArray;
  }


  public PrimitiveArraysObjectWithRestrictions bShortArray(List<Integer> bShortArray) {
    this.bShortArray = bShortArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addBShortArrayItem(Integer bShortArrayItem) {
    if (this.bShortArray == null) {
      this.bShortArray = new ArrayList<>();
    }
    this.bShortArray.add(bShortArrayItem);
    return this;
  }

   /**
   * Get bShortArray
   * @return bShortArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_SHORT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getbShortArray() {
    return bShortArray;
  }


  @JsonProperty(JSON_PROPERTY_B_SHORT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbShortArray(List<Integer> bShortArray) {
    this.bShortArray = bShortArray;
  }


  public PrimitiveArraysObjectWithRestrictions aIntegerArray(List<Integer> aIntegerArray) {
    this.aIntegerArray = aIntegerArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addAIntegerArrayItem(Integer aIntegerArrayItem) {
    if (this.aIntegerArray == null) {
      this.aIntegerArray = new ArrayList<>();
    }
    this.aIntegerArray.add(aIntegerArrayItem);
    return this;
  }

   /**
   * Get aIntegerArray
   * @return aIntegerArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getaIntegerArray() {
    return aIntegerArray;
  }


  @JsonProperty(JSON_PROPERTY_A_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaIntegerArray(List<Integer> aIntegerArray) {
    this.aIntegerArray = aIntegerArray;
  }


  public PrimitiveArraysObjectWithRestrictions bIntegerArray(List<Integer> bIntegerArray) {
    this.bIntegerArray = bIntegerArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addBIntegerArrayItem(Integer bIntegerArrayItem) {
    if (this.bIntegerArray == null) {
      this.bIntegerArray = new ArrayList<>();
    }
    this.bIntegerArray.add(bIntegerArrayItem);
    return this;
  }

   /**
   * Get bIntegerArray
   * @return bIntegerArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getbIntegerArray() {
    return bIntegerArray;
  }


  @JsonProperty(JSON_PROPERTY_B_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbIntegerArray(List<Integer> bIntegerArray) {
    this.bIntegerArray = bIntegerArray;
  }


  public PrimitiveArraysObjectWithRestrictions cIntegerArray(List<Integer> cIntegerArray) {
    this.cIntegerArray = cIntegerArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addCIntegerArrayItem(Integer cIntegerArrayItem) {
    if (this.cIntegerArray == null) {
      this.cIntegerArray = new ArrayList<>();
    }
    this.cIntegerArray.add(cIntegerArrayItem);
    return this;
  }

   /**
   * Get cIntegerArray
   * @return cIntegerArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_C_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getcIntegerArray() {
    return cIntegerArray;
  }


  @JsonProperty(JSON_PROPERTY_C_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcIntegerArray(List<Integer> cIntegerArray) {
    this.cIntegerArray = cIntegerArray;
  }


  public PrimitiveArraysObjectWithRestrictions aLongArray(List<Long> aLongArray) {
    this.aLongArray = aLongArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addALongArrayItem(Long aLongArrayItem) {
    this.aLongArray.add(aLongArrayItem);
    return this;
  }

   /**
   * Get aLongArray
   * @return aLongArray
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_A_LONG_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Long> getaLongArray() {
    return aLongArray;
  }


  @JsonProperty(JSON_PROPERTY_A_LONG_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setaLongArray(List<Long> aLongArray) {
    this.aLongArray = aLongArray;
  }


  public PrimitiveArraysObjectWithRestrictions bLongArray(List<Long> bLongArray) {
    this.bLongArray = bLongArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addBLongArrayItem(Long bLongArrayItem) {
    if (this.bLongArray == null) {
      this.bLongArray = new ArrayList<>();
    }
    this.bLongArray.add(bLongArrayItem);
    return this;
  }

   /**
   * Get bLongArray
   * @return bLongArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_LONG_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getbLongArray() {
    return bLongArray;
  }


  @JsonProperty(JSON_PROPERTY_B_LONG_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbLongArray(List<Long> bLongArray) {
    this.bLongArray = bLongArray;
  }


  public PrimitiveArraysObjectWithRestrictions aBigIntegerArray(List<Long> aBigIntegerArray) {
    this.aBigIntegerArray = aBigIntegerArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addABigIntegerArrayItem(Long aBigIntegerArrayItem) {
    if (this.aBigIntegerArray == null) {
      this.aBigIntegerArray = new ArrayList<>();
    }
    this.aBigIntegerArray.add(aBigIntegerArrayItem);
    return this;
  }

   /**
   * Get aBigIntegerArray
   * @return aBigIntegerArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_BIG_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getaBigIntegerArray() {
    return aBigIntegerArray;
  }


  @JsonProperty(JSON_PROPERTY_A_BIG_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaBigIntegerArray(List<Long> aBigIntegerArray) {
    this.aBigIntegerArray = aBigIntegerArray;
  }


  public PrimitiveArraysObjectWithRestrictions aCharacterArray(List<String> aCharacterArray) {
    this.aCharacterArray = aCharacterArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addACharacterArrayItem(String aCharacterArrayItem) {
    if (this.aCharacterArray == null) {
      this.aCharacterArray = new ArrayList<>();
    }
    this.aCharacterArray.add(aCharacterArrayItem);
    return this;
  }

   /**
   * Get aCharacterArray
   * @return aCharacterArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_CHARACTER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getaCharacterArray() {
    return aCharacterArray;
  }


  @JsonProperty(JSON_PROPERTY_A_CHARACTER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaCharacterArray(List<String> aCharacterArray) {
    this.aCharacterArray = aCharacterArray;
  }


  public PrimitiveArraysObjectWithRestrictions bCharacterArray(List<String> bCharacterArray) {
    this.bCharacterArray = bCharacterArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addBCharacterArrayItem(String bCharacterArrayItem) {
    if (this.bCharacterArray == null) {
      this.bCharacterArray = new ArrayList<>();
    }
    this.bCharacterArray.add(bCharacterArrayItem);
    return this;
  }

   /**
   * Get bCharacterArray
   * @return bCharacterArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_CHARACTER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getbCharacterArray() {
    return bCharacterArray;
  }


  @JsonProperty(JSON_PROPERTY_B_CHARACTER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbCharacterArray(List<String> bCharacterArray) {
    this.bCharacterArray = bCharacterArray;
  }


  public PrimitiveArraysObjectWithRestrictions aFloatArray(List<Float> aFloatArray) {
    this.aFloatArray = aFloatArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addAFloatArrayItem(Float aFloatArrayItem) {
    if (this.aFloatArray == null) {
      this.aFloatArray = new ArrayList<>();
    }
    this.aFloatArray.add(aFloatArrayItem);
    return this;
  }

   /**
   * Get aFloatArray
   * @return aFloatArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_FLOAT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getaFloatArray() {
    return aFloatArray;
  }


  @JsonProperty(JSON_PROPERTY_A_FLOAT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaFloatArray(List<Float> aFloatArray) {
    this.aFloatArray = aFloatArray;
  }


  public PrimitiveArraysObjectWithRestrictions bFloatArray(List<Float> bFloatArray) {
    this.bFloatArray = bFloatArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addBFloatArrayItem(Float bFloatArrayItem) {
    if (this.bFloatArray == null) {
      this.bFloatArray = new ArrayList<>();
    }
    this.bFloatArray.add(bFloatArrayItem);
    return this;
  }

   /**
   * Get bFloatArray
   * @return bFloatArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_FLOAT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getbFloatArray() {
    return bFloatArray;
  }


  @JsonProperty(JSON_PROPERTY_B_FLOAT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbFloatArray(List<Float> bFloatArray) {
    this.bFloatArray = bFloatArray;
  }


  public PrimitiveArraysObjectWithRestrictions aDoubleArray(List<Double> aDoubleArray) {
    this.aDoubleArray = aDoubleArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addADoubleArrayItem(Double aDoubleArrayItem) {
    if (this.aDoubleArray == null) {
      this.aDoubleArray = new ArrayList<>();
    }
    this.aDoubleArray.add(aDoubleArrayItem);
    return this;
  }

   /**
   * Get aDoubleArray
   * @return aDoubleArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_DOUBLE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Double> getaDoubleArray() {
    return aDoubleArray;
  }


  @JsonProperty(JSON_PROPERTY_A_DOUBLE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaDoubleArray(List<Double> aDoubleArray) {
    this.aDoubleArray = aDoubleArray;
  }


  public PrimitiveArraysObjectWithRestrictions bDoubleArray(List<Double> bDoubleArray) {
    this.bDoubleArray = bDoubleArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addBDoubleArrayItem(Double bDoubleArrayItem) {
    if (this.bDoubleArray == null) {
      this.bDoubleArray = new ArrayList<>();
    }
    this.bDoubleArray.add(bDoubleArrayItem);
    return this;
  }

   /**
   * Get bDoubleArray
   * @return bDoubleArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_DOUBLE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Double> getbDoubleArray() {
    return bDoubleArray;
  }


  @JsonProperty(JSON_PROPERTY_B_DOUBLE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbDoubleArray(List<Double> bDoubleArray) {
    this.bDoubleArray = bDoubleArray;
  }


  public PrimitiveArraysObjectWithRestrictions aBigDecimalArray(List<Double> aBigDecimalArray) {
    this.aBigDecimalArray = aBigDecimalArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addABigDecimalArrayItem(Double aBigDecimalArrayItem) {
    if (this.aBigDecimalArray == null) {
      this.aBigDecimalArray = new ArrayList<>();
    }
    this.aBigDecimalArray.add(aBigDecimalArrayItem);
    return this;
  }

   /**
   * Get aBigDecimalArray
   * @return aBigDecimalArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_BIG_DECIMAL_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Double> getaBigDecimalArray() {
    return aBigDecimalArray;
  }


  @JsonProperty(JSON_PROPERTY_A_BIG_DECIMAL_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaBigDecimalArray(List<Double> aBigDecimalArray) {
    this.aBigDecimalArray = aBigDecimalArray;
  }


  public PrimitiveArraysObjectWithRestrictions aStringArray(List<String> aStringArray) {
    this.aStringArray = aStringArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addAStringArrayItem(String aStringArrayItem) {
    if (this.aStringArray == null) {
      this.aStringArray = new ArrayList<>();
    }
    this.aStringArray.add(aStringArrayItem);
    return this;
  }

   /**
   * Get aStringArray
   * @return aStringArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_STRING_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getaStringArray() {
    return aStringArray;
  }


  @JsonProperty(JSON_PROPERTY_A_STRING_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaStringArray(List<String> aStringArray) {
    this.aStringArray = aStringArray;
  }


  public PrimitiveArraysObjectWithRestrictions bStringArray(List<String> bStringArray) {
    this.bStringArray = bStringArray;
    return this;
  }

  public PrimitiveArraysObjectWithRestrictions addBStringArrayItem(String bStringArrayItem) {
    if (this.bStringArray == null) {
      this.bStringArray = new ArrayList<>();
    }
    this.bStringArray.add(bStringArrayItem);
    return this;
  }

   /**
   * Get bStringArray
   * @return bStringArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_STRING_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getbStringArray() {
    return bStringArray;
  }


  @JsonProperty(JSON_PROPERTY_B_STRING_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbStringArray(List<String> bStringArray) {
    this.bStringArray = bStringArray;
  }


  /**
   * Return true if this PrimitiveArraysObjectWithRestrictions object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrimitiveArraysObjectWithRestrictions primitiveArraysObjectWithRestrictions = (PrimitiveArraysObjectWithRestrictions) o;
    return Objects.equals(this.aBooleanArray, primitiveArraysObjectWithRestrictions.aBooleanArray) &&
        Objects.equals(this.bBooleanArray, primitiveArraysObjectWithRestrictions.bBooleanArray) &&
        Objects.equals(this.cBooleanArray, primitiveArraysObjectWithRestrictions.cBooleanArray) &&
        Arrays.equals(this.aByteArray, primitiveArraysObjectWithRestrictions.aByteArray) &&
        Arrays.equals(this.bByteArray, primitiveArraysObjectWithRestrictions.bByteArray) &&
        Objects.equals(this.aShortArray, primitiveArraysObjectWithRestrictions.aShortArray) &&
        Objects.equals(this.bShortArray, primitiveArraysObjectWithRestrictions.bShortArray) &&
        Objects.equals(this.aIntegerArray, primitiveArraysObjectWithRestrictions.aIntegerArray) &&
        Objects.equals(this.bIntegerArray, primitiveArraysObjectWithRestrictions.bIntegerArray) &&
        Objects.equals(this.cIntegerArray, primitiveArraysObjectWithRestrictions.cIntegerArray) &&
        Objects.equals(this.aLongArray, primitiveArraysObjectWithRestrictions.aLongArray) &&
        Objects.equals(this.bLongArray, primitiveArraysObjectWithRestrictions.bLongArray) &&
        Objects.equals(this.aBigIntegerArray, primitiveArraysObjectWithRestrictions.aBigIntegerArray) &&
        Objects.equals(this.aCharacterArray, primitiveArraysObjectWithRestrictions.aCharacterArray) &&
        Objects.equals(this.bCharacterArray, primitiveArraysObjectWithRestrictions.bCharacterArray) &&
        Objects.equals(this.aFloatArray, primitiveArraysObjectWithRestrictions.aFloatArray) &&
        Objects.equals(this.bFloatArray, primitiveArraysObjectWithRestrictions.bFloatArray) &&
        Objects.equals(this.aDoubleArray, primitiveArraysObjectWithRestrictions.aDoubleArray) &&
        Objects.equals(this.bDoubleArray, primitiveArraysObjectWithRestrictions.bDoubleArray) &&
        Objects.equals(this.aBigDecimalArray, primitiveArraysObjectWithRestrictions.aBigDecimalArray) &&
        Objects.equals(this.aStringArray, primitiveArraysObjectWithRestrictions.aStringArray) &&
        Objects.equals(this.bStringArray, primitiveArraysObjectWithRestrictions.bStringArray);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aBooleanArray, bBooleanArray, cBooleanArray, Arrays.hashCode(aByteArray), Arrays.hashCode(bByteArray), aShortArray, bShortArray, aIntegerArray, bIntegerArray, cIntegerArray, aLongArray, bLongArray, aBigIntegerArray, aCharacterArray, bCharacterArray, aFloatArray, bFloatArray, aDoubleArray, bDoubleArray, aBigDecimalArray, aStringArray, bStringArray);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrimitiveArraysObjectWithRestrictions {\n");
    sb.append("    aBooleanArray: ").append(toIndentedString(aBooleanArray)).append("\n");
    sb.append("    bBooleanArray: ").append(toIndentedString(bBooleanArray)).append("\n");
    sb.append("    cBooleanArray: ").append(toIndentedString(cBooleanArray)).append("\n");
    sb.append("    aByteArray: ").append(toIndentedString(aByteArray)).append("\n");
    sb.append("    bByteArray: ").append(toIndentedString(bByteArray)).append("\n");
    sb.append("    aShortArray: ").append(toIndentedString(aShortArray)).append("\n");
    sb.append("    bShortArray: ").append(toIndentedString(bShortArray)).append("\n");
    sb.append("    aIntegerArray: ").append(toIndentedString(aIntegerArray)).append("\n");
    sb.append("    bIntegerArray: ").append(toIndentedString(bIntegerArray)).append("\n");
    sb.append("    cIntegerArray: ").append(toIndentedString(cIntegerArray)).append("\n");
    sb.append("    aLongArray: ").append(toIndentedString(aLongArray)).append("\n");
    sb.append("    bLongArray: ").append(toIndentedString(bLongArray)).append("\n");
    sb.append("    aBigIntegerArray: ").append(toIndentedString(aBigIntegerArray)).append("\n");
    sb.append("    aCharacterArray: ").append(toIndentedString(aCharacterArray)).append("\n");
    sb.append("    bCharacterArray: ").append(toIndentedString(bCharacterArray)).append("\n");
    sb.append("    aFloatArray: ").append(toIndentedString(aFloatArray)).append("\n");
    sb.append("    bFloatArray: ").append(toIndentedString(bFloatArray)).append("\n");
    sb.append("    aDoubleArray: ").append(toIndentedString(aDoubleArray)).append("\n");
    sb.append("    bDoubleArray: ").append(toIndentedString(bDoubleArray)).append("\n");
    sb.append("    aBigDecimalArray: ").append(toIndentedString(aBigDecimalArray)).append("\n");
    sb.append("    aStringArray: ").append(toIndentedString(aStringArray)).append("\n");
    sb.append("    bStringArray: ").append(toIndentedString(bStringArray)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

