/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * PrimitiveArraysObject
 */
@JsonPropertyOrder({
  PrimitiveArraysObject.JSON_PROPERTY_A_BOOLEAN_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_B_BOOLEAN_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_C_BOOLEAN_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_A_BYTE_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_B_BYTE_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_A_SHORT_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_B_SHORT_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_A_INTEGER_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_B_INTEGER_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_C_INTEGER_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_A_LONG_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_B_LONG_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_A_BIG_INTEGER_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_A_CHARACTER_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_B_CHARACTER_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_A_FLOAT_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_B_FLOAT_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_A_DOUBLE_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_B_DOUBLE_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_A_BIG_DECIMAL_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_A_STRING_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_B_STRING_ARRAY,
  PrimitiveArraysObject.JSON_PROPERTY_C_STRING_ARRAY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PrimitiveArraysObject {
  public static final String JSON_PROPERTY_A_BOOLEAN_ARRAY = "aBooleanArray";
  private List<Boolean> aBooleanArray = null;

  public static final String JSON_PROPERTY_B_BOOLEAN_ARRAY = "bBooleanArray";
  private List<Boolean> bBooleanArray = null;

  public static final String JSON_PROPERTY_C_BOOLEAN_ARRAY = "cBooleanArray";
  private List<Boolean> cBooleanArray = null;

  public static final String JSON_PROPERTY_A_BYTE_ARRAY = "aByteArray";
  private byte[] aByteArray;

  public static final String JSON_PROPERTY_B_BYTE_ARRAY = "bByteArray";
  private byte[] bByteArray;

  public static final String JSON_PROPERTY_A_SHORT_ARRAY = "aShortArray";
  private List<Integer> aShortArray = null;

  public static final String JSON_PROPERTY_B_SHORT_ARRAY = "bShortArray";
  private List<Integer> bShortArray = null;

  public static final String JSON_PROPERTY_A_INTEGER_ARRAY = "aIntegerArray";
  private List<Integer> aIntegerArray = null;

  public static final String JSON_PROPERTY_B_INTEGER_ARRAY = "bIntegerArray";
  private List<Integer> bIntegerArray = null;

  public static final String JSON_PROPERTY_C_INTEGER_ARRAY = "cIntegerArray";
  private List<Integer> cIntegerArray = null;

  public static final String JSON_PROPERTY_A_LONG_ARRAY = "aLongArray";
  private List<Long> aLongArray = null;

  public static final String JSON_PROPERTY_B_LONG_ARRAY = "bLongArray";
  private List<Long> bLongArray = null;

  public static final String JSON_PROPERTY_A_BIG_INTEGER_ARRAY = "aBigIntegerArray";
  private List<Long> aBigIntegerArray = null;

  public static final String JSON_PROPERTY_A_CHARACTER_ARRAY = "aCharacterArray";
  private List<String> aCharacterArray = null;

  public static final String JSON_PROPERTY_B_CHARACTER_ARRAY = "bCharacterArray";
  private List<String> bCharacterArray = null;

  public static final String JSON_PROPERTY_A_FLOAT_ARRAY = "aFloatArray";
  private List<Float> aFloatArray = null;

  public static final String JSON_PROPERTY_B_FLOAT_ARRAY = "bFloatArray";
  private List<Float> bFloatArray = null;

  public static final String JSON_PROPERTY_A_DOUBLE_ARRAY = "aDoubleArray";
  private List<Double> aDoubleArray = null;

  public static final String JSON_PROPERTY_B_DOUBLE_ARRAY = "bDoubleArray";
  private List<Double> bDoubleArray = null;

  public static final String JSON_PROPERTY_A_BIG_DECIMAL_ARRAY = "aBigDecimalArray";
  private List<Double> aBigDecimalArray = null;

  public static final String JSON_PROPERTY_A_STRING_ARRAY = "aStringArray";
  private List<String> aStringArray = null;

  public static final String JSON_PROPERTY_B_STRING_ARRAY = "bStringArray";
  private List<String> bStringArray = null;

  public static final String JSON_PROPERTY_C_STRING_ARRAY = "cStringArray";
  private List<String> cStringArray = new ArrayList<>();

  public PrimitiveArraysObject() { 
  }

  public PrimitiveArraysObject aBooleanArray(List<Boolean> aBooleanArray) {
    this.aBooleanArray = aBooleanArray;
    return this;
  }

  public PrimitiveArraysObject addABooleanArrayItem(Boolean aBooleanArrayItem) {
    if (this.aBooleanArray == null) {
      this.aBooleanArray = new ArrayList<>();
    }
    this.aBooleanArray.add(aBooleanArrayItem);
    return this;
  }

   /**
   * Get aBooleanArray
   * @return aBooleanArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_BOOLEAN_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Boolean> getaBooleanArray() {
    return aBooleanArray;
  }


  @JsonProperty(JSON_PROPERTY_A_BOOLEAN_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaBooleanArray(List<Boolean> aBooleanArray) {
    this.aBooleanArray = aBooleanArray;
  }


  public PrimitiveArraysObject bBooleanArray(List<Boolean> bBooleanArray) {
    this.bBooleanArray = bBooleanArray;
    return this;
  }

  public PrimitiveArraysObject addBBooleanArrayItem(Boolean bBooleanArrayItem) {
    if (this.bBooleanArray == null) {
      this.bBooleanArray = new ArrayList<>();
    }
    this.bBooleanArray.add(bBooleanArrayItem);
    return this;
  }

   /**
   * Get bBooleanArray
   * @return bBooleanArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_BOOLEAN_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Boolean> getbBooleanArray() {
    return bBooleanArray;
  }


  @JsonProperty(JSON_PROPERTY_B_BOOLEAN_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbBooleanArray(List<Boolean> bBooleanArray) {
    this.bBooleanArray = bBooleanArray;
  }


  public PrimitiveArraysObject cBooleanArray(List<Boolean> cBooleanArray) {
    this.cBooleanArray = cBooleanArray;
    return this;
  }

  public PrimitiveArraysObject addCBooleanArrayItem(Boolean cBooleanArrayItem) {
    if (this.cBooleanArray == null) {
      this.cBooleanArray = new ArrayList<>();
    }
    this.cBooleanArray.add(cBooleanArrayItem);
    return this;
  }

   /**
   * Get cBooleanArray
   * @return cBooleanArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_C_BOOLEAN_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Boolean> getcBooleanArray() {
    return cBooleanArray;
  }


  @JsonProperty(JSON_PROPERTY_C_BOOLEAN_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcBooleanArray(List<Boolean> cBooleanArray) {
    this.cBooleanArray = cBooleanArray;
  }


  public PrimitiveArraysObject aByteArray(byte[] aByteArray) {
    this.aByteArray = aByteArray;
    return this;
  }

   /**
   * Get aByteArray
   * @return aByteArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_BYTE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getaByteArray() {
    return aByteArray;
  }


  @JsonProperty(JSON_PROPERTY_A_BYTE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaByteArray(byte[] aByteArray) {
    this.aByteArray = aByteArray;
  }


  public PrimitiveArraysObject bByteArray(byte[] bByteArray) {
    this.bByteArray = bByteArray;
    return this;
  }

   /**
   * Get bByteArray
   * @return bByteArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_BYTE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getbByteArray() {
    return bByteArray;
  }


  @JsonProperty(JSON_PROPERTY_B_BYTE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbByteArray(byte[] bByteArray) {
    this.bByteArray = bByteArray;
  }


  public PrimitiveArraysObject aShortArray(List<Integer> aShortArray) {
    this.aShortArray = aShortArray;
    return this;
  }

  public PrimitiveArraysObject addAShortArrayItem(Integer aShortArrayItem) {
    if (this.aShortArray == null) {
      this.aShortArray = new ArrayList<>();
    }
    this.aShortArray.add(aShortArrayItem);
    return this;
  }

   /**
   * Get aShortArray
   * @return aShortArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_SHORT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getaShortArray() {
    return aShortArray;
  }


  @JsonProperty(JSON_PROPERTY_A_SHORT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaShortArray(List<Integer> aShortArray) {
    this.aShortArray = aShortArray;
  }


  public PrimitiveArraysObject bShortArray(List<Integer> bShortArray) {
    this.bShortArray = bShortArray;
    return this;
  }

  public PrimitiveArraysObject addBShortArrayItem(Integer bShortArrayItem) {
    if (this.bShortArray == null) {
      this.bShortArray = new ArrayList<>();
    }
    this.bShortArray.add(bShortArrayItem);
    return this;
  }

   /**
   * Get bShortArray
   * @return bShortArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_SHORT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getbShortArray() {
    return bShortArray;
  }


  @JsonProperty(JSON_PROPERTY_B_SHORT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbShortArray(List<Integer> bShortArray) {
    this.bShortArray = bShortArray;
  }


  public PrimitiveArraysObject aIntegerArray(List<Integer> aIntegerArray) {
    this.aIntegerArray = aIntegerArray;
    return this;
  }

  public PrimitiveArraysObject addAIntegerArrayItem(Integer aIntegerArrayItem) {
    if (this.aIntegerArray == null) {
      this.aIntegerArray = new ArrayList<>();
    }
    this.aIntegerArray.add(aIntegerArrayItem);
    return this;
  }

   /**
   * Get aIntegerArray
   * @return aIntegerArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getaIntegerArray() {
    return aIntegerArray;
  }


  @JsonProperty(JSON_PROPERTY_A_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaIntegerArray(List<Integer> aIntegerArray) {
    this.aIntegerArray = aIntegerArray;
  }


  public PrimitiveArraysObject bIntegerArray(List<Integer> bIntegerArray) {
    this.bIntegerArray = bIntegerArray;
    return this;
  }

  public PrimitiveArraysObject addBIntegerArrayItem(Integer bIntegerArrayItem) {
    if (this.bIntegerArray == null) {
      this.bIntegerArray = new ArrayList<>();
    }
    this.bIntegerArray.add(bIntegerArrayItem);
    return this;
  }

   /**
   * Get bIntegerArray
   * @return bIntegerArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getbIntegerArray() {
    return bIntegerArray;
  }


  @JsonProperty(JSON_PROPERTY_B_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbIntegerArray(List<Integer> bIntegerArray) {
    this.bIntegerArray = bIntegerArray;
  }


  public PrimitiveArraysObject cIntegerArray(List<Integer> cIntegerArray) {
    this.cIntegerArray = cIntegerArray;
    return this;
  }

  public PrimitiveArraysObject addCIntegerArrayItem(Integer cIntegerArrayItem) {
    if (this.cIntegerArray == null) {
      this.cIntegerArray = new ArrayList<>();
    }
    this.cIntegerArray.add(cIntegerArrayItem);
    return this;
  }

   /**
   * Get cIntegerArray
   * @return cIntegerArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_C_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getcIntegerArray() {
    return cIntegerArray;
  }


  @JsonProperty(JSON_PROPERTY_C_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcIntegerArray(List<Integer> cIntegerArray) {
    this.cIntegerArray = cIntegerArray;
  }


  public PrimitiveArraysObject aLongArray(List<Long> aLongArray) {
    this.aLongArray = aLongArray;
    return this;
  }

  public PrimitiveArraysObject addALongArrayItem(Long aLongArrayItem) {
    if (this.aLongArray == null) {
      this.aLongArray = new ArrayList<>();
    }
    this.aLongArray.add(aLongArrayItem);
    return this;
  }

   /**
   * Get aLongArray
   * @return aLongArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_LONG_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getaLongArray() {
    return aLongArray;
  }


  @JsonProperty(JSON_PROPERTY_A_LONG_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaLongArray(List<Long> aLongArray) {
    this.aLongArray = aLongArray;
  }


  public PrimitiveArraysObject bLongArray(List<Long> bLongArray) {
    this.bLongArray = bLongArray;
    return this;
  }

  public PrimitiveArraysObject addBLongArrayItem(Long bLongArrayItem) {
    if (this.bLongArray == null) {
      this.bLongArray = new ArrayList<>();
    }
    this.bLongArray.add(bLongArrayItem);
    return this;
  }

   /**
   * Get bLongArray
   * @return bLongArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_LONG_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getbLongArray() {
    return bLongArray;
  }


  @JsonProperty(JSON_PROPERTY_B_LONG_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbLongArray(List<Long> bLongArray) {
    this.bLongArray = bLongArray;
  }


  public PrimitiveArraysObject aBigIntegerArray(List<Long> aBigIntegerArray) {
    this.aBigIntegerArray = aBigIntegerArray;
    return this;
  }

  public PrimitiveArraysObject addABigIntegerArrayItem(Long aBigIntegerArrayItem) {
    if (this.aBigIntegerArray == null) {
      this.aBigIntegerArray = new ArrayList<>();
    }
    this.aBigIntegerArray.add(aBigIntegerArrayItem);
    return this;
  }

   /**
   * Get aBigIntegerArray
   * @return aBigIntegerArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_BIG_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getaBigIntegerArray() {
    return aBigIntegerArray;
  }


  @JsonProperty(JSON_PROPERTY_A_BIG_INTEGER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaBigIntegerArray(List<Long> aBigIntegerArray) {
    this.aBigIntegerArray = aBigIntegerArray;
  }


  public PrimitiveArraysObject aCharacterArray(List<String> aCharacterArray) {
    this.aCharacterArray = aCharacterArray;
    return this;
  }

  public PrimitiveArraysObject addACharacterArrayItem(String aCharacterArrayItem) {
    if (this.aCharacterArray == null) {
      this.aCharacterArray = new ArrayList<>();
    }
    this.aCharacterArray.add(aCharacterArrayItem);
    return this;
  }

   /**
   * Get aCharacterArray
   * @return aCharacterArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_CHARACTER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getaCharacterArray() {
    return aCharacterArray;
  }


  @JsonProperty(JSON_PROPERTY_A_CHARACTER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaCharacterArray(List<String> aCharacterArray) {
    this.aCharacterArray = aCharacterArray;
  }


  public PrimitiveArraysObject bCharacterArray(List<String> bCharacterArray) {
    this.bCharacterArray = bCharacterArray;
    return this;
  }

  public PrimitiveArraysObject addBCharacterArrayItem(String bCharacterArrayItem) {
    if (this.bCharacterArray == null) {
      this.bCharacterArray = new ArrayList<>();
    }
    this.bCharacterArray.add(bCharacterArrayItem);
    return this;
  }

   /**
   * Get bCharacterArray
   * @return bCharacterArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_CHARACTER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getbCharacterArray() {
    return bCharacterArray;
  }


  @JsonProperty(JSON_PROPERTY_B_CHARACTER_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbCharacterArray(List<String> bCharacterArray) {
    this.bCharacterArray = bCharacterArray;
  }


  public PrimitiveArraysObject aFloatArray(List<Float> aFloatArray) {
    this.aFloatArray = aFloatArray;
    return this;
  }

  public PrimitiveArraysObject addAFloatArrayItem(Float aFloatArrayItem) {
    if (this.aFloatArray == null) {
      this.aFloatArray = new ArrayList<>();
    }
    this.aFloatArray.add(aFloatArrayItem);
    return this;
  }

   /**
   * Get aFloatArray
   * @return aFloatArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_FLOAT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getaFloatArray() {
    return aFloatArray;
  }


  @JsonProperty(JSON_PROPERTY_A_FLOAT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaFloatArray(List<Float> aFloatArray) {
    this.aFloatArray = aFloatArray;
  }


  public PrimitiveArraysObject bFloatArray(List<Float> bFloatArray) {
    this.bFloatArray = bFloatArray;
    return this;
  }

  public PrimitiveArraysObject addBFloatArrayItem(Float bFloatArrayItem) {
    if (this.bFloatArray == null) {
      this.bFloatArray = new ArrayList<>();
    }
    this.bFloatArray.add(bFloatArrayItem);
    return this;
  }

   /**
   * Get bFloatArray
   * @return bFloatArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_FLOAT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getbFloatArray() {
    return bFloatArray;
  }


  @JsonProperty(JSON_PROPERTY_B_FLOAT_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbFloatArray(List<Float> bFloatArray) {
    this.bFloatArray = bFloatArray;
  }


  public PrimitiveArraysObject aDoubleArray(List<Double> aDoubleArray) {
    this.aDoubleArray = aDoubleArray;
    return this;
  }

  public PrimitiveArraysObject addADoubleArrayItem(Double aDoubleArrayItem) {
    if (this.aDoubleArray == null) {
      this.aDoubleArray = new ArrayList<>();
    }
    this.aDoubleArray.add(aDoubleArrayItem);
    return this;
  }

   /**
   * Get aDoubleArray
   * @return aDoubleArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_DOUBLE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Double> getaDoubleArray() {
    return aDoubleArray;
  }


  @JsonProperty(JSON_PROPERTY_A_DOUBLE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaDoubleArray(List<Double> aDoubleArray) {
    this.aDoubleArray = aDoubleArray;
  }


  public PrimitiveArraysObject bDoubleArray(List<Double> bDoubleArray) {
    this.bDoubleArray = bDoubleArray;
    return this;
  }

  public PrimitiveArraysObject addBDoubleArrayItem(Double bDoubleArrayItem) {
    if (this.bDoubleArray == null) {
      this.bDoubleArray = new ArrayList<>();
    }
    this.bDoubleArray.add(bDoubleArrayItem);
    return this;
  }

   /**
   * Get bDoubleArray
   * @return bDoubleArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_DOUBLE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Double> getbDoubleArray() {
    return bDoubleArray;
  }


  @JsonProperty(JSON_PROPERTY_B_DOUBLE_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbDoubleArray(List<Double> bDoubleArray) {
    this.bDoubleArray = bDoubleArray;
  }


  public PrimitiveArraysObject aBigDecimalArray(List<Double> aBigDecimalArray) {
    this.aBigDecimalArray = aBigDecimalArray;
    return this;
  }

  public PrimitiveArraysObject addABigDecimalArrayItem(Double aBigDecimalArrayItem) {
    if (this.aBigDecimalArray == null) {
      this.aBigDecimalArray = new ArrayList<>();
    }
    this.aBigDecimalArray.add(aBigDecimalArrayItem);
    return this;
  }

   /**
   * Get aBigDecimalArray
   * @return aBigDecimalArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_BIG_DECIMAL_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Double> getaBigDecimalArray() {
    return aBigDecimalArray;
  }


  @JsonProperty(JSON_PROPERTY_A_BIG_DECIMAL_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaBigDecimalArray(List<Double> aBigDecimalArray) {
    this.aBigDecimalArray = aBigDecimalArray;
  }


  public PrimitiveArraysObject aStringArray(List<String> aStringArray) {
    this.aStringArray = aStringArray;
    return this;
  }

  public PrimitiveArraysObject addAStringArrayItem(String aStringArrayItem) {
    if (this.aStringArray == null) {
      this.aStringArray = new ArrayList<>();
    }
    this.aStringArray.add(aStringArrayItem);
    return this;
  }

   /**
   * Get aStringArray
   * @return aStringArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_STRING_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getaStringArray() {
    return aStringArray;
  }


  @JsonProperty(JSON_PROPERTY_A_STRING_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaStringArray(List<String> aStringArray) {
    this.aStringArray = aStringArray;
  }


  public PrimitiveArraysObject bStringArray(List<String> bStringArray) {
    this.bStringArray = bStringArray;
    return this;
  }

  public PrimitiveArraysObject addBStringArrayItem(String bStringArrayItem) {
    if (this.bStringArray == null) {
      this.bStringArray = new ArrayList<>();
    }
    this.bStringArray.add(bStringArrayItem);
    return this;
  }

   /**
   * Get bStringArray
   * @return bStringArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_STRING_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getbStringArray() {
    return bStringArray;
  }


  @JsonProperty(JSON_PROPERTY_B_STRING_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setbStringArray(List<String> bStringArray) {
    this.bStringArray = bStringArray;
  }


  public PrimitiveArraysObject cStringArray(List<String> cStringArray) {
    this.cStringArray = cStringArray;
    return this;
  }

  public PrimitiveArraysObject addCStringArrayItem(String cStringArrayItem) {
    this.cStringArray.add(cStringArrayItem);
    return this;
  }

   /**
   * Get cStringArray
   * @return cStringArray
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_C_STRING_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getcStringArray() {
    return cStringArray;
  }


  @JsonProperty(JSON_PROPERTY_C_STRING_ARRAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setcStringArray(List<String> cStringArray) {
    this.cStringArray = cStringArray;
  }


  /**
   * Return true if this PrimitiveArraysObject object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrimitiveArraysObject primitiveArraysObject = (PrimitiveArraysObject) o;
    return Objects.equals(this.aBooleanArray, primitiveArraysObject.aBooleanArray) &&
        Objects.equals(this.bBooleanArray, primitiveArraysObject.bBooleanArray) &&
        Objects.equals(this.cBooleanArray, primitiveArraysObject.cBooleanArray) &&
        Arrays.equals(this.aByteArray, primitiveArraysObject.aByteArray) &&
        Arrays.equals(this.bByteArray, primitiveArraysObject.bByteArray) &&
        Objects.equals(this.aShortArray, primitiveArraysObject.aShortArray) &&
        Objects.equals(this.bShortArray, primitiveArraysObject.bShortArray) &&
        Objects.equals(this.aIntegerArray, primitiveArraysObject.aIntegerArray) &&
        Objects.equals(this.bIntegerArray, primitiveArraysObject.bIntegerArray) &&
        Objects.equals(this.cIntegerArray, primitiveArraysObject.cIntegerArray) &&
        Objects.equals(this.aLongArray, primitiveArraysObject.aLongArray) &&
        Objects.equals(this.bLongArray, primitiveArraysObject.bLongArray) &&
        Objects.equals(this.aBigIntegerArray, primitiveArraysObject.aBigIntegerArray) &&
        Objects.equals(this.aCharacterArray, primitiveArraysObject.aCharacterArray) &&
        Objects.equals(this.bCharacterArray, primitiveArraysObject.bCharacterArray) &&
        Objects.equals(this.aFloatArray, primitiveArraysObject.aFloatArray) &&
        Objects.equals(this.bFloatArray, primitiveArraysObject.bFloatArray) &&
        Objects.equals(this.aDoubleArray, primitiveArraysObject.aDoubleArray) &&
        Objects.equals(this.bDoubleArray, primitiveArraysObject.bDoubleArray) &&
        Objects.equals(this.aBigDecimalArray, primitiveArraysObject.aBigDecimalArray) &&
        Objects.equals(this.aStringArray, primitiveArraysObject.aStringArray) &&
        Objects.equals(this.bStringArray, primitiveArraysObject.bStringArray) &&
        Objects.equals(this.cStringArray, primitiveArraysObject.cStringArray);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aBooleanArray, bBooleanArray, cBooleanArray, Arrays.hashCode(aByteArray), Arrays.hashCode(bByteArray), aShortArray, bShortArray, aIntegerArray, bIntegerArray, cIntegerArray, aLongArray, bLongArray, aBigIntegerArray, aCharacterArray, bCharacterArray, aFloatArray, bFloatArray, aDoubleArray, bDoubleArray, aBigDecimalArray, aStringArray, bStringArray, cStringArray);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrimitiveArraysObject {\n");
    sb.append("    aBooleanArray: ").append(toIndentedString(aBooleanArray)).append("\n");
    sb.append("    bBooleanArray: ").append(toIndentedString(bBooleanArray)).append("\n");
    sb.append("    cBooleanArray: ").append(toIndentedString(cBooleanArray)).append("\n");
    sb.append("    aByteArray: ").append(toIndentedString(aByteArray)).append("\n");
    sb.append("    bByteArray: ").append(toIndentedString(bByteArray)).append("\n");
    sb.append("    aShortArray: ").append(toIndentedString(aShortArray)).append("\n");
    sb.append("    bShortArray: ").append(toIndentedString(bShortArray)).append("\n");
    sb.append("    aIntegerArray: ").append(toIndentedString(aIntegerArray)).append("\n");
    sb.append("    bIntegerArray: ").append(toIndentedString(bIntegerArray)).append("\n");
    sb.append("    cIntegerArray: ").append(toIndentedString(cIntegerArray)).append("\n");
    sb.append("    aLongArray: ").append(toIndentedString(aLongArray)).append("\n");
    sb.append("    bLongArray: ").append(toIndentedString(bLongArray)).append("\n");
    sb.append("    aBigIntegerArray: ").append(toIndentedString(aBigIntegerArray)).append("\n");
    sb.append("    aCharacterArray: ").append(toIndentedString(aCharacterArray)).append("\n");
    sb.append("    bCharacterArray: ").append(toIndentedString(bCharacterArray)).append("\n");
    sb.append("    aFloatArray: ").append(toIndentedString(aFloatArray)).append("\n");
    sb.append("    bFloatArray: ").append(toIndentedString(bFloatArray)).append("\n");
    sb.append("    aDoubleArray: ").append(toIndentedString(aDoubleArray)).append("\n");
    sb.append("    bDoubleArray: ").append(toIndentedString(bDoubleArray)).append("\n");
    sb.append("    aBigDecimalArray: ").append(toIndentedString(aBigDecimalArray)).append("\n");
    sb.append("    aStringArray: ").append(toIndentedString(aStringArray)).append("\n");
    sb.append("    bStringArray: ").append(toIndentedString(bStringArray)).append("\n");
    sb.append("    cStringArray: ").append(toIndentedString(cStringArray)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

