/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * TechParent
 */
@JsonPropertyOrder({
  TechParent.JSON_PROPERTY_TECH_ATTRIBUTE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class TechParent {
  public static final String JSON_PROPERTY_TECH_ATTRIBUTE = "techAttribute";
  @javax.annotation.Nonnull
  private String techAttribute;

  public TechParent() { 
  }

  public TechParent techAttribute(@javax.annotation.Nonnull String techAttribute) {
    this.techAttribute = techAttribute;
    return this;
  }

  /**
   * Get techAttribute
   * @return techAttribute
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TECH_ATTRIBUTE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTechAttribute() {
    return techAttribute;
  }


  @JsonProperty(value = JSON_PROPERTY_TECH_ATTRIBUTE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTechAttribute(@javax.annotation.Nonnull String techAttribute) {
    this.techAttribute = techAttribute;
  }


  /**
   * Return true if this TechParent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TechParent techParent = (TechParent) o;
    return Objects.equals(this.techAttribute, techParent.techAttribute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(techAttribute);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TechParent {\n");
    sb.append("    techAttribute: ").append(toIndentedString(techAttribute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

