/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Enumeration represents time units.&lt;br&gt;      &lt;br&gt; NOVA 14 Mapping&lt;br&gt; * nova-base.xsd.ZeitEinheit &lt;br&gt;&lt;br&gt; Alternate Name: &#x60;Zeiteinheit&#x60; &lt;br&gt; Valid Values:  - &#x60;MINUTE&#x60;: Literal represents time unit \&quot;minutes\&quot;.   &lt;br&gt;&lt;br&gt;    - &#x60;HOUR&#x60;   &lt;br&gt;&lt;br&gt;    - &#x60;DAY&#x60;   &lt;br&gt;&lt;br&gt;    - &#x60;WEEK&#x60;: Literal represents time unit \&quot;weeks\&quot;.&lt;br&gt;   This is the comments second line ;-)   &lt;br&gt;&lt;br&gt;    - &#x60;MONTH&#x60;   &lt;br&gt;&lt;br&gt;    - &#x60;YEAR&#x60;   &lt;br&gt;&lt;br&gt;    
 */
public enum TimeUnit {
  
  MINUTE("MINUTE"),
  
  HOUR("HOUR"),
  
  DAY("DAY"),
  
  WEEK("WEEK"),
  
  MONTH("MONTH"),
  
  YEAR("YEAR");

  private String value;

  TimeUnit(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TimeUnit fromValue(String value) {
    for (TimeUnit b : TimeUnit.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

