/*
 * Product Base Definitions
 * This component represents the Open API interface of the accounting service.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jeaf@anaptecs.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import openapitools.model.ComplexBookingID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import openapitools.JSON;


/**
 * WeirdBooking
 */
@JsonPropertyOrder({
  WeirdBooking.JSON_PROPERTY_BOOKING,
  WeirdBooking.JSON_PROPERTY_ADDITIONAL_BOOKINGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WeirdBooking {
  public static final String JSON_PROPERTY_BOOKING = "booking";
  private ComplexBookingID booking;

  public static final String JSON_PROPERTY_ADDITIONAL_BOOKINGS = "additionalBookings";
  private List<ComplexBookingID> additionalBookings = null;

  public WeirdBooking() { 
  }

  public WeirdBooking booking(ComplexBookingID booking) {
    this.booking = booking;
    return this;
  }

   /**
   * Get booking
   * @return booking
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BOOKING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ComplexBookingID getBooking() {
    return booking;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBooking(ComplexBookingID booking) {
    this.booking = booking;
  }


  public WeirdBooking additionalBookings(List<ComplexBookingID> additionalBookings) {
    this.additionalBookings = additionalBookings;
    return this;
  }

  public WeirdBooking addAdditionalBookingsItem(ComplexBookingID additionalBookingsItem) {
    if (this.additionalBookings == null) {
      this.additionalBookings = new ArrayList<>();
    }
    this.additionalBookings.add(additionalBookingsItem);
    return this;
  }

   /**
   * Get additionalBookings
   * @return additionalBookings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_BOOKINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ComplexBookingID> getAdditionalBookings() {
    return additionalBookings;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_BOOKINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalBookings(List<ComplexBookingID> additionalBookings) {
    this.additionalBookings = additionalBookings;
  }


  /**
   * Return true if this WeirdBooking object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WeirdBooking weirdBooking = (WeirdBooking) o;
    return Objects.equals(this.booking, weirdBooking.booking) &&
        Objects.equals(this.additionalBookings, weirdBooking.additionalBookings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(booking, additionalBookings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WeirdBooking {\n");
    sb.append("    booking: ").append(toIndentedString(booking)).append("\n");
    sb.append("    additionalBookings: ").append(toIndentedString(additionalBookings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

