<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>


	<groupId>com.anaptecs.maven</groupId>
	<artifactId>jeaf-generator-other-service-model</artifactId>
	<version>47.1.1</version>

	<packaging>pom</packaging>
	<name>JEAF Generator Other Service Model</name>


	<!-- Custom section for information about developers -->
	<!-- PROTECTED REGION ID(developers:com.anaptecs.maven:jeaf-generator-other-service-model) ENABLED START -->
	<!-- Everything that is within this protection area will remain unchanged by JEAF Generator. -->
	<!--
	<developers>
		<developer>
			<name></name>
			<email></email>
			<organization></organization>
			<organizationUrl></organizationUrl>
		</developer>
	</developers>
	-->
	<!-- PROTECTED REGION END -->


	<scm>
		<connection>scm:git:https://github.com/anaptecs/jeaf-generator-other-service-model>.git</connection>
		<developerConnection>scm:git:https://github.com/anaptecs/jeaf-generator-other-service-model>.git</developerConnection>
		<url>https://github.com/anaptecs/jeaf-generator-other-service-model></url>
		<tag>HEAD</tag>
	</scm>


	<!-- Custom section for distribution management -->
	<distributionManagement>
		<!-- PROTECTED REGION ID(distributionManagement:com.anaptecs.maven:jeaf-generator-other-service-model) ENABLED START -->
		<!-- Everything that is within this protection area will remain unchanged by JEAF Generator. -->
		<!-- PROTECTED REGION END -->
	</distributionManagement>


	<!-- Custom section for license information -->
	<!-- PROTECTED REGION ID(licenses:com.anaptecs.maven:jeaf-generator-other-service-model) ENABLED START -->
	<!-- Everything that is within this protection area will remain unchanged by JEAF Generator. -->
	<!--
	<licenses>
		<license>
			<name>The Apache License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
		</license>
	</licenses>
	-->
	<!-- PROTECTED REGION END -->


	<properties>
		<!-- Read UML model from Maven artifact. -->
		<modelArtifactGroupID>com.anaptecs.jeaf.uml</modelArtifactGroupID>
		<modelArtifactArtifactID>jeaf-uml-test-model</modelArtifactArtifactID>
		<modelArtifactXMIPath>xmi</modelArtifactXMIPath>

		<!-- Name of the main file with the UML model -->
		<umlModelFile>JEAF_Test.uml</umlModelFile>

		<!-- UML package which will be the one that is considered during code generation --> 
		<umlPackage>com.anaptecs.maven</umlPackage>

		<!-- Custom section for properties -->
		<!-- PROTECTED REGION ID(properties:com.anaptecs.maven:jeaf-generator-other-service-model) ENABLED START -->
		<!-- Everything that is within this protection area will remain unchanged by JEAF Generator. -->
		<!-- Add your custom properties here -->
		<!-- PROTECTED REGION END -->
	</properties>


	<modules>
		<module>jeaf-generator-other-service-model-bom</module>
		<module>jeaf-generator-other-service-model-uml</module>
		<module>jeaf-generator-other-service-model-open-api</module>
		<module>jeaf-generator-other-service-model-java</module>
		<module>jeaf-generator-other-service-model-java-runtime</module>
		<module>jeaf-generator-other-service-model-services</module>
		<module>jeaf-generator-other-service-model-rest-client</module>
		<module>jeaf-generator-other-service-model-rest-client-starter</module>
		<module>jeaf-generator-other-service-model-rest-controller</module>
		<module>jeaf-generator-other-service-model-rest-controller-starter</module>
		<module>jeaf-generator-other-service-model-integration-test</module>
	</modules>


	<dependencyManagement>
		<dependencies>
			<!-- Section for custom dependency management entries -->
			<!-- PROTECTED REGION ID(dependencyManagement:com.anaptecs.maven:jeaf-generator-other-service-model) ENABLED START -->
			<!-- Everything that is within this protection area will remain unchanged by JEAF Generator. -->
			<!-- PROTECTED REGION END -->
		</dependencies>
	</dependencyManagement>


	<dependencies>

		<!-- Custom section for dependencies -->
		<!-- PROTECTED REGION ID(dependencies:com.anaptecs.maven:jeaf-generator-other-service-model-) ENABLED START -->
		<!-- Everything that is within this protection area will remain unchanged by JEAF Generator. -->
		<!-- Add your custom properties here -->
		<!-- PROTECTED REGION END -->
	</dependencies>


	<profiles>
		<!-- Section for custom profile entries -->
		<!-- PROTECTED REGION ID(profiles:com.anaptecs.maven:jeaf-generator-other-service-model) ENABLED START -->
		<!-- Everything that is within this protection area will remain unchanged by JEAF Generator. -->
		<!-- PROTECTED REGION END -->
	</profiles>


	<build>
		<plugins>
			<!-- Section for custom plugin entries -->
			<!-- PROTECTED REGION ID(plugins:com.anaptecs.maven:jeaf-generator-other-service-model) ENABLED START -->
			<!-- Everything that is within this protection area will remain unchanged by JEAF Generator. -->
			<!-- PROTECTED REGION END -->
		</plugins>
	</build>
</project>
