/*
 * anaptecs GmbH, Ricarda-Huch-Str. 71, 72760 Reutlingen, Germany
 *
 * Copyright 2004 - 2019. All rights reserved.
 */
package com.anaptecs.jeaf.junit.core;

import java.util.Set;

import com.anaptecs.jeaf.core.api.Service;
import com.anaptecs.jeaf.core.api.ServiceObjectID;

/**
 * The BusinessObjectTest service provides methods that can be used to tests JEAFs implementation of business objects.
 * All the offered method will be used by JEAF JUnit tests.<br/>
 * <br/>
 * This is a multi line comment
 * <p/>
 * This is the second comment of this service. This is just intended to test JEAF Generator.
 * <p/>
 *
 * @author JEAF Generator
 * @version JEAF Release 1.4.x
 */
public interface BusinessObjectTestService extends Service {
  /**
   */
  void testAttributeAccess( );

  /**
   */
  void testBusinessMethods( );

  /**
   * Method tests the business objects that are generated by the JEAF Generator. This test cases cares about
   * many-to-many associations between service objects.<br/>
   */
  void testBusinessObjectsWithManyToManyAssociations( );

  /**
   * Method tests the business objects that are generated by the JEAF Generator. This test cases cares about one-to-many
   * associations between service objects.<br/>
   */
  void testServiceObjectsWithOneToManyAssociations( );

  /**
   * Method tests the business objects that are generated by the JEAF Generator. This test cases cares about one-to-one
   * associations between service objects.<br/>
   */
  void testServiceObjectsWithOneToOneAssociations( );

  /**
   */
  void testCreateSimpleBusinessObject( );

  /**
   */
  void testBusinessObjectsWithInheritance( );

  /**
   */
  void testMToNReleation( );

  /**
   * Method updates the business object with the passed id.
   *
   * @param pServiceObjectID
   * @return {@link Integer}
   */
  Integer updateBusinessObject( ServiceObjectID pServiceObjectID );

  /**
   * @return {@link ServiceObjectID}
   */
  ServiceObjectID createBusinessObject( );

  /**
   * @param pServiceObjectID
   */
  void deleteBusinessObject( ServiceObjectID pServiceObjectID );

  /**
   */
  void testQueryWithJPAQL( );

  /**
   */
  void testAOneToBOne( );

  /**
   */
  void testBOneToAOne( );

  /**
   */
  void createXOne( );

  /**
   * @return {@link ServiceObjectID}
   */
  ServiceObjectID createABCObjects( );

  /**
   */
  void testNativeQuery( );

  /**
   * @param pBOneID
   * @return {@link Set<ServiceObjectID>}
   */
  Set<ServiceObjectID> getCManys( ServiceObjectID pBOneID );

  /**
   * @param pBOneID
   * @return {@link ServiceObjectID}
   */
  ServiceObjectID addCMany( ServiceObjectID pBOneID );

  /**
   * @param pBOneID
   */
  void clearCMany( ServiceObjectID pBOneID );

  /**
   * @param pBOneID
   * @param pCManyID
   */
  void removeCMany( ServiceObjectID pBOneID, ServiceObjectID pCManyID );

  /**
   */
  void testDynamicPropertyAccess( );

  /**
   */
  void testCreateBusinessObjectsWithUserTypeMapping( );

  /**
   */
  void testReadBusinessObjectsWithUserTypeMapping( );

  /**
   * @param pClassA
   * @return {@link ClassA}
   */
  ClassA createClassA( ClassA pClassA );

  /**
   * @param pClassA
   */
  void updateClassA( ClassA pClassA );

  /**
   * @param pServiceObjectID
   * @return {@link ClassA}
   */
  ClassA getClassA( ServiceObjectID pServiceObjectID );

  /**
   */
  void testInitialObjectCache( );

  /**
   */
  void testObjectCacheReloading( );

  /**
   */
  void testJDBCWorker( );

  /**
   * @param pFail
   */
  void testTransactionListener( boolean pFail );

  /**
   */
  void testFlush( );

  /**
   */
  @Deprecated
  void deprectedOperation( );
}
